// Code generated by tools/generate_types from https://docs.kalshi.com/openapi.yaml — DO NOT EDIT.
// Source: types_generated.go

package gokalshi

// AcceptQuoteRequest is a generated type from the Kalshi OpenAPI spec.
type AcceptQuoteRequest struct {
	// The side of the quote to accept (yes or no)
	AcceptedSide string `json:"accepted_side"`
}

// AmendOrderRequest is a generated type from the Kalshi OpenAPI spec.
type AmendOrderRequest struct {
	// Action of the order
	Action Action `json:"action"`
	// The original client-specified order ID to be amended
	ClientOrderID string `json:"client_order_id,omitempty"`
	// Updated quantity for the order (whole contracts only). If updating quantity, provide count or cou...
	Count int `json:"count,omitempty"`
	// String representation of the updated quantity for the order. If updating quantity, provide count ...
	CountFP *string `json:"count_fp,omitempty"`
	// Updated no price for the order in cents
	NoPrice int `json:"no_price,omitempty"`
	// Updated no price for the order in fixed-point dollars. Exactly one of yes_price, no_price, yes_pr...
	NoPriceDollars string `json:"no_price_dollars,omitempty"`
	// Side of the order
	Side Side `json:"side"`
	// Optional subaccount number to use for this amendment (0 for primary, 1-32 for subaccounts)
	Subaccount int `json:"subaccount,omitempty"`
	// Market ticker
	Ticker string `json:"ticker"`
	// The new client-specified order ID after amendment
	UpdatedClientOrderID string `json:"updated_client_order_id,omitempty"`
	// Updated yes price for the order in cents
	YesPrice int `json:"yes_price,omitempty"`
	// Updated yes price for the order in fixed-point dollars. Exactly one of yes_price, no_price, yes_p...
	YesPriceDollars string `json:"yes_price_dollars,omitempty"`
}

// Order is a generated type from the Kalshi OpenAPI spec.
type Order struct {
	Action Action `json:"action"`
	// If this flag is set to true, the order will be canceled if the order is open and trading on the e...
	CancelOrderOnPause bool    `json:"cancel_order_on_pause,omitempty"`
	ClientOrderID      string  `json:"client_order_id"`
	CreatedTime        *string `json:"created_time,omitempty"`
	ExpirationTime     *string `json:"expiration_time,omitempty"`
	// String representation of the number of contracts that have been filled
	FillCountFP string `json:"fill_count_fp"`
	// String representation of the initial size of the order (contract units)
	InitialCountFP string `json:"initial_count_fp"`
	// The last update to an order (modify, cancel, fill)
	LastUpdateTime *string `json:"last_update_time,omitempty"`
	// Fees paid on filled maker contracts, in dollars
	MakerFeesDollars string `json:"maker_fees_dollars"`
	// The cost of filled maker orders in dollars
	MakerFillCostDollars string `json:"maker_fill_cost_dollars"`
	// The no price for this order in fixed-point dollars
	NoPriceDollars string `json:"no_price_dollars"`
	// The order group this order is part of
	OrderGroupID *string `json:"order_group_id,omitempty"`
	OrderID      string  `json:"order_id"`
	// String representation of the remaining contracts for this order
	RemainingCountFP        string                   `json:"remaining_count_fp"`
	SelfTradePreventionType *SelfTradePreventionType `json:"self_trade_prevention_type,omitempty"`
	Side                    Side                     `json:"side"`
	Status                  OrderStatus              `json:"status"`
	// Subaccount number (0 for primary, 1-32 for subaccounts).
	SubaccountNumber *int `json:"subaccount_number,omitempty"`
	// Fees paid on filled taker contracts, in dollars
	TakerFeesDollars string `json:"taker_fees_dollars"`
	// The cost of filled taker orders in dollars
	TakerFillCostDollars string    `json:"taker_fill_cost_dollars"`
	Ticker               string    `json:"ticker"`
	Type                 OrderType `json:"type"`
	// Unique identifier for users
	UserID string `json:"user_id"`
	// The yes price for this order in fixed-point dollars
	YesPriceDollars string `json:"yes_price_dollars"`
}

// AmendOrderResponse is a generated type from the Kalshi OpenAPI spec.
type AmendOrderResponse struct {
	// The order before amendment
	OldOrder Order `json:"old_order"`
	// The order after amendment
	Order Order `json:"order"`
}

// AmendOrderV2Request is a generated type from the Kalshi OpenAPI spec.
type AmendOrderV2Request struct {
	// The original client-specified order ID to be amended
	ClientOrderID string `json:"client_order_id,omitempty"`
	// String representation of the updated quantity for the order.
	Count string `json:"count"`
	// Updated price for the order in fixed-point dollars.
	Price string `json:"price"`
	// Side of the order
	Side BookSide `json:"side"`
	// Market ticker
	Ticker string `json:"ticker"`
	// The new client-specified order ID after amendment
	UpdatedClientOrderID string `json:"updated_client_order_id,omitempty"`
}

// AmendOrderV2Response is a generated type from the Kalshi OpenAPI spec.
type AmendOrderV2Response struct {
	// Volume-weighted average fee paid per contract for fills resulting from the amend. Only present wh...
	AverageFeePaid *string `json:"average_fee_paid,omitempty"`
	// Volume-weighted average fill price for fills resulting from the amend. Only present when fills oc...
	AverageFillPrice *string `json:"average_fill_price,omitempty"`
	ClientOrderID    string  `json:"client_order_id,omitempty"`
	// Number of contracts filled as a result of the amend crossing the book. Only present when fills oc...
	FillCount *string `json:"fill_count,omitempty"`
	OrderID   string  `json:"order_id"`
	// Number of contracts remaining after the amend. Only present when the amend caused a fill or chang...
	RemainingCount *string `json:"remaining_count,omitempty"`
}

// Announcement is a generated type from the Kalshi OpenAPI spec.
type Announcement struct {
	// The time the announcement was delivered.
	DeliveryTime string `json:"delivery_time"`
	// The message contained within the announcement.
	Message string `json:"message"`
	// The current status of this announcement.
	Status AnnouncementStatus `json:"status"`
	// The type of the announcement.
	Type AnnouncementType `json:"type"`
}

// ApiKey is a generated type from the Kalshi OpenAPI spec.
type ApiKey struct {
	// Unique identifier for the API key
	APIKeyID string `json:"api_key_id"`
	// User-provided name for the API key
	Name string `json:"name"`
	// List of scopes granted to this API key. Valid values are 'read' and 'write'.
	Scopes []string `json:"scopes"`
}

// ApplySubaccountTransferRequest is a generated type from the Kalshi OpenAPI spec.
type ApplySubaccountTransferRequest struct {
	// Amount to transfer in cents.
	AmountCents int64 `json:"amount_cents"`
	// Unique client-provided transfer ID for idempotency.
	ClientTransferID string `json:"client_transfer_id"`
	// Source subaccount number (0 for primary, 1-32 for numbered subaccounts).
	FromSubaccount int `json:"from_subaccount"`
	// Destination subaccount number (0 for primary, 1-32 for numbered subaccounts).
	ToSubaccount int `json:"to_subaccount"`
}

// ApplySubaccountTransferResponse Empty response indicating successful transfer.
type ApplySubaccountTransferResponse struct {
}

// AssociatedEvent is a generated type from the Kalshi OpenAPI spec.
type AssociatedEvent struct {
	// List of active quoters for this event.
	ActiveQuoters []string `json:"active_quoters"`
	// Whether only the 'yes' side can be used for this event.
	IsYesOnly bool `json:"is_yes_only"`
	// Maximum number of markets from this event (inclusive). Null means no limit.
	SizeMax *int `json:"size_max,omitempty"`
	// Minimum number of markets from this event (inclusive). Null means no limit.
	SizeMin *int `json:"size_min,omitempty"`
	// The event ticker.
	Ticker string `json:"ticker"`
}

// ErrorResponse is a generated type from the Kalshi OpenAPI spec.
type ErrorResponse struct {
	// Error code
	Code string `json:"code,omitempty"`
	// Additional details about the error, if available
	Details string `json:"details,omitempty"`
	// Human-readable error message
	Message string `json:"message,omitempty"`
	// The name of the service that generated the error
	Service string `json:"service,omitempty"`
}

// BatchCancelOrdersIndividualResponse is a generated type from the Kalshi OpenAPI spec.
type BatchCancelOrdersIndividualResponse struct {
	Error *ErrorResponse `json:"error,omitempty"`
	Order *Order         `json:"order,omitempty"`
	// The order ID to identify which order had an error during batch cancellation
	OrderID string `json:"order_id"`
	// String representation of the number of contracts that were successfully canceled from this order
	ReducedByFP string `json:"reduced_by_fp"`
}

// BatchCancelOrdersRequestOrder is a generated type from the Kalshi OpenAPI spec.
type BatchCancelOrdersRequestOrder struct {
	// Order ID to cancel
	OrderID string `json:"order_id"`
	// Optional subaccount number to use for this cancellation (0 for primary, 1-32 for subaccounts)
	Subaccount int `json:"subaccount,omitempty"`
}

// BatchCancelOrdersRequest is a generated type from the Kalshi OpenAPI spec.
type BatchCancelOrdersRequest struct {
	// An array of order IDs to cancel
	// Deprecated.
	Ids []string `json:"ids,omitempty"`
	// An array of orders to cancel, each optionally specifying a subaccount
	Orders []BatchCancelOrdersRequestOrder `json:"orders,omitempty"`
}

// BatchCancelOrdersResponse is a generated type from the Kalshi OpenAPI spec.
type BatchCancelOrdersResponse struct {
	Orders []BatchCancelOrdersIndividualResponse `json:"orders"`
}

// BatchCancelOrdersV2Request is a generated type from the Kalshi OpenAPI spec.
type BatchCancelOrdersV2Request struct {
	// An array of orders to cancel, each optionally specifying a subaccount.
	Orders []map[string]any `json:"orders"`
}

// BatchCancelOrdersV2Response is a generated type from the Kalshi OpenAPI spec.
type BatchCancelOrdersV2Response struct {
	Orders []map[string]any `json:"orders"`
}

// BatchCreateOrdersIndividualResponse is a generated type from the Kalshi OpenAPI spec.
type BatchCreateOrdersIndividualResponse struct {
	ClientOrderID *string        `json:"client_order_id,omitempty"`
	Error         *ErrorResponse `json:"error,omitempty"`
	Order         *Order         `json:"order,omitempty"`
}

// CreateOrderRequest is a generated type from the Kalshi OpenAPI spec.
type CreateOrderRequest struct {
	Action Action `json:"action"`
	// Maximum cost in cents. When specified, the order will automatically have Fill-or-Kill (FoK) behav...
	BuyMaxCost int `json:"buy_max_cost,omitempty"`
	// If this flag is set to true, the order will be canceled if the order is open and trading on the e...
	CancelOrderOnPause bool   `json:"cancel_order_on_pause,omitempty"`
	ClientOrderID      string `json:"client_order_id,omitempty"`
	// Order quantity in contracts (whole contracts only). Provide count or count_fp; if both provided t...
	Count int `json:"count,omitempty"`
	// String representation of the order quantity in contracts. Provide count or count_fp; if both prov...
	CountFP      *string `json:"count_fp,omitempty"`
	ExpirationTS int64   `json:"expiration_ts,omitempty"`
	NoPrice      int     `json:"no_price,omitempty"`
	// Submitting price of the No side in fixed-point dollars
	NoPriceDollars string `json:"no_price_dollars,omitempty"`
	// The order group this order is part of
	OrderGroupID            string                  `json:"order_group_id,omitempty"`
	PostOnly                bool                    `json:"post_only,omitempty"`
	ReduceOnly              bool                    `json:"reduce_only,omitempty"`
	SelfTradePreventionType SelfTradePreventionType `json:"self_trade_prevention_type,omitempty"`
	// Deprecated: Use reduce_only instead. Only accepts value of 0.
	SellPositionFloor int  `json:"sell_position_floor,omitempty"`
	Side              Side `json:"side"`
	// The subaccount number to use for this order. 0 is the primary subaccount.
	Subaccount  int         `json:"subaccount,omitempty"`
	Ticker      string      `json:"ticker"`
	TimeInForce TimeInForce `json:"time_in_force,omitempty"`
	YesPrice    int         `json:"yes_price,omitempty"`
	// Submitting price of the Yes side in fixed-point dollars
	YesPriceDollars string `json:"yes_price_dollars,omitempty"`
}

// BatchCreateOrdersRequest is a generated type from the Kalshi OpenAPI spec.
type BatchCreateOrdersRequest struct {
	Orders []CreateOrderRequest `json:"orders"`
}

// BatchCreateOrdersResponse is a generated type from the Kalshi OpenAPI spec.
type BatchCreateOrdersResponse struct {
	Orders []BatchCreateOrdersIndividualResponse `json:"orders"`
}

// CreateOrderV2Request is a generated type from the Kalshi OpenAPI spec.
type CreateOrderV2Request struct {
	// If this flag is set to true, the order will be canceled if the order is open and trading on the e...
	CancelOrderOnPause bool   `json:"cancel_order_on_pause,omitempty"`
	ClientOrderID      string `json:"client_order_id"`
	// String representation of the order quantity in contracts.
	Count          string `json:"count"`
	ExpirationTime int64  `json:"expiration_time,omitempty"`
	// The order group this order is part of
	OrderGroupID string `json:"order_group_id,omitempty"`
	PostOnly     bool   `json:"post_only,omitempty"`
	// Price for the order in fixed-point dollars.
	Price string `json:"price"`
	// Specifies whether the order place count should be capped by the member's current position.
	ReduceOnly              bool                    `json:"reduce_only,omitempty"`
	SelfTradePreventionType SelfTradePreventionType `json:"self_trade_prevention_type"`
	Side                    BookSide                `json:"side"`
	// The subaccount number to use for this order. 0 is the primary subaccount.
	Subaccount  int    `json:"subaccount,omitempty"`
	Ticker      string `json:"ticker"`
	TimeInForce string `json:"time_in_force"`
}

// BatchCreateOrdersV2Request is a generated type from the Kalshi OpenAPI spec.
type BatchCreateOrdersV2Request struct {
	Orders []CreateOrderV2Request `json:"orders"`
}

// BatchCreateOrdersV2Response is a generated type from the Kalshi OpenAPI spec.
type BatchCreateOrdersV2Response struct {
	Orders []map[string]any `json:"orders"`
}

// BidAskDistribution is a generated type from the Kalshi OpenAPI spec.
type BidAskDistribution struct {
	// Offer price on the market at the end of the candlestick period (in dollars).
	CloseDollars string `json:"close_dollars"`
	// Highest offer price on the market during the candlestick period (in dollars).
	HighDollars string `json:"high_dollars"`
	// Lowest offer price on the market during the candlestick period (in dollars).
	LowDollars string `json:"low_dollars"`
	// Offer price on the market at the start of the candlestick period (in dollars).
	OpenDollars string `json:"open_dollars"`
}

// PriceDistribution is a generated type from the Kalshi OpenAPI spec.
type PriceDistribution struct {
	// Last traded YES contract price on the market during the candlestick period (in dollars). May be n...
	CloseDollars *string `json:"close_dollars,omitempty"`
	// Highest traded YES contract price on the market during the candlestick period (in dollars). May b...
	HighDollars *string `json:"high_dollars,omitempty"`
	// Lowest traded YES contract price on the market during the candlestick period (in dollars). May be...
	LowDollars *string `json:"low_dollars,omitempty"`
	// Maximum close price of any market during the candlestick period (in dollars).
	MaxDollars *string `json:"max_dollars,omitempty"`
	// Mean traded YES contract price on the market during the candlestick period (in dollars). May be n...
	MeanDollars *string `json:"mean_dollars,omitempty"`
	// Minimum close price of any market during the candlestick period (in dollars).
	MinDollars *string `json:"min_dollars,omitempty"`
	// First traded YES contract price on the market during the candlestick period (in dollars). May be ...
	OpenDollars *string `json:"open_dollars,omitempty"`
	// Last traded YES contract price on the market before the candlestick period (in dollars). May be n...
	PreviousDollars *string `json:"previous_dollars,omitempty"`
}

// MarketCandlestick is a generated type from the Kalshi OpenAPI spec.
type MarketCandlestick struct {
	// Unix timestamp for the inclusive end of the candlestick period.
	EndPeriodTS int64 `json:"end_period_ts"`
	// String representation of the number of contracts bought on the market by end of the candlestick p...
	OpenInterestFP string `json:"open_interest_fp"`
	// Open, high, low, close (OHLC) and more data for trade YES contract prices on the market during th...
	Price PriceDistribution `json:"price"`
	// String representation of the number of contracts bought on the market during the candlestick period.
	VolumeFP string `json:"volume_fp"`
	// Open, high, low, close (OHLC) data for YES sell offers on the market during the candlestick period.
	YesAsk BidAskDistribution `json:"yes_ask"`
	// Open, high, low, close (OHLC) data for YES buy offers on the market during the candlestick period.
	YesBid BidAskDistribution `json:"yes_bid"`
}

// MarketCandlesticksResponse is a generated type from the Kalshi OpenAPI spec.
type MarketCandlesticksResponse struct {
	// Array of candlestick data points for the market. Includes an initial data point at the start time...
	Candlesticks []MarketCandlestick `json:"candlesticks"`
	// Market ticker string (e.g., 'INXD-24JAN01').
	MarketTicker string `json:"market_ticker"`
}

// BatchGetMarketCandlesticksResponse is a generated type from the Kalshi OpenAPI spec.
type BatchGetMarketCandlesticksResponse struct {
	// Array of market candlestick data, one entry per requested market.
	Markets []MarketCandlesticksResponse `json:"markets"`
}

// BidAskDistributionHistorical is a generated type from the Kalshi OpenAPI spec.
type BidAskDistributionHistorical struct {
	// Offer price on the market at the end of the candlestick period (in dollars).
	Close string `json:"close"`
	// Highest offer price on the market during the candlestick period (in dollars).
	High string `json:"high"`
	// Lowest offer price on the market during the candlestick period (in dollars).
	Low string `json:"low"`
	// Offer price on the market at the start of the candlestick period (in dollars).
	Open string `json:"open"`
}

// BucketLimit Token-bucket budget for one rate-limit bucket. Each request deducts
type BucketLimit struct {
	// Maximum tokens the bucket can hold. When equal to refill_rate the
	BucketCapacity int `json:"bucket_capacity"`
	// Tokens added to the bucket per second.
	RefillRate int `json:"refill_rate"`
}

// CancelOrderResponse is a generated type from the Kalshi OpenAPI spec.
type CancelOrderResponse struct {
	Order Order `json:"order"`
	// String representation of the number of contracts that were successfully canceled from this order
	ReducedByFP string `json:"reduced_by_fp"`
}

// CancelOrderV2Response is a generated type from the Kalshi OpenAPI spec.
type CancelOrderV2Response struct {
	ClientOrderID string `json:"client_order_id,omitempty"`
	OrderID       string `json:"order_id"`
	// Number of contracts that were canceled (i.e. the remaining count at time of cancellation).
	ReducedBy string `json:"reduced_by"`
}

// CreateApiKeyRequest is a generated type from the Kalshi OpenAPI spec.
type CreateApiKeyRequest struct {
	// Name for the API key. This helps identify the key's purpose
	Name string `json:"name"`
	// RSA public key in PEM format. This will be used to verify signatures on API requests
	PublicKey string `json:"public_key"`
	// List of scopes to grant to the API key. Valid values are 'read' and 'write'. If 'write' is includ...
	Scopes []string `json:"scopes,omitempty"`
}

// CreateApiKeyResponse is a generated type from the Kalshi OpenAPI spec.
type CreateApiKeyResponse struct {
	// Unique identifier for the newly created API key
	APIKeyID string `json:"api_key_id"`
}

// TickerPair is a generated type from the Kalshi OpenAPI spec.
type TickerPair struct {
	// Event ticker identifier.
	EventTicker string `json:"event_ticker"`
	// Market ticker identifier.
	MarketTicker string `json:"market_ticker"`
	// Side of the market (yes or no).
	Side string `json:"side"`
}

// CreateMarketInMultivariateEventCollectionRequest is a generated type from the Kalshi OpenAPI spec.
type CreateMarketInMultivariateEventCollectionRequest struct {
	// List of selected markets that act as parameters to determine which market is created.
	SelectedMarkets []TickerPair `json:"selected_markets"`
	// Whether to include the market payload in the response.
	WithMarketPayload bool `json:"with_market_payload,omitempty"`
}

// MveSelectedLeg is a generated type from the Kalshi OpenAPI spec.
type MveSelectedLeg struct {
	// Unique identifier for the selected event
	EventTicker string `json:"event_ticker,omitempty"`
	// Unique identifier for the selected market
	MarketTicker string `json:"market_ticker,omitempty"`
	// The side of the selected market
	Side Side `json:"side,omitempty"`
	// The settlement value of the YES/LONG side of the contract in dollars. Only filled after determina...
	YesSettlementValueDollars *string `json:"yes_settlement_value_dollars,omitempty"`
}

// PriceRange is a generated type from the Kalshi OpenAPI spec.
type PriceRange struct {
	// Ending price for this range in dollars
	End string `json:"end"`
	// Starting price for this range in dollars
	Start string `json:"start"`
	// Price step/tick size for this range in dollars
	Step string `json:"step"`
}

// Market is a generated type from the Kalshi OpenAPI spec.
type Market struct {
	CanCloseEarly bool `json:"can_close_early"`
	// Maximum expiration value that leads to a YES settlement
	CapStrike   *float64 `json:"cap_strike,omitempty"`
	CloseTime   string   `json:"close_time"`
	CreatedTime string   `json:"created_time"`
	// Expiration value for each target that leads to a YES settlement
	CustomStrike map[string]any `json:"custom_strike,omitempty"`
	// The condition under which the market can close early
	EarlyCloseCondition *string `json:"early_close_condition,omitempty"`
	EventTicker         string  `json:"event_ticker"`
	// Time when this market is expected to expire
	ExpectedExpirationTime *string `json:"expected_expiration_time,omitempty"`
	// Deprecated.
	ExpirationTime string `json:"expiration_time,omitempty"`
	// The value that was considered for the settlement
	ExpirationValue string `json:"expiration_value"`
	// Time when this market's fee waiver expires
	FeeWaiverExpirationTime *string `json:"fee_waiver_expiration_time,omitempty"`
	// Minimum expiration value that leads to a YES settlement
	FloorStrike              *float64 `json:"floor_strike,omitempty"`
	FractionalTradingEnabled bool     `json:"fractional_trading_enabled"`
	// Mapping from expiration values to settlement values
	FunctionalStrike *string `json:"functional_strike,omitempty"`
	// If true, the market may be removed after determination if there is no activity on it
	IsProvisional bool `json:"is_provisional,omitempty"`
	// Price for the last traded YES contract on this market in dollars
	LastPriceDollars string `json:"last_price_dollars"`
	// Latest possible time for this market to expire
	LatestExpirationTime string `json:"latest_expiration_time"`
	// DEPRECATED: This field is deprecated and will always return "0.0000".
	// Deprecated.
	LiquidityDollars string `json:"liquidity_dollars"`
	// Identifies the type of market
	MarketType MarketType `json:"market_type"`
	// The ticker of the multivariate event collection
	MVECollectionTicker string           `json:"mve_collection_ticker,omitempty"`
	MVESelectedLegs     []MveSelectedLeg `json:"mve_selected_legs,omitempty"`
	// Price for the lowest NO sell offer on this market in dollars
	NoAskDollars string `json:"no_ask_dollars"`
	// Price for the highest NO buy offer on this market in dollars
	NoBidDollars string `json:"no_bid_dollars"`
	// Shortened title for the no side of this market
	NoSubTitle string `json:"no_sub_title"`
	// The total value of a single contract at settlement in dollars
	NotionalValueDollars string `json:"notional_value_dollars"`
	// The recorded datetime when the underlying event occurred, if available
	OccurrenceDatetime *string `json:"occurrence_datetime,omitempty"`
	// String representation of the number of contracts bought on this market disconsidering netting
	OpenInterestFP string `json:"open_interest_fp"`
	OpenTime       string `json:"open_time"`
	// Price for the last traded YES contract on this market a day ago in dollars
	PreviousPriceDollars string `json:"previous_price_dollars"`
	// Price for the lowest YES sell offer on this market a day ago in dollars
	PreviousYesAskDollars string `json:"previous_yes_ask_dollars"`
	// Price for the highest YES buy offer on this market a day ago in dollars
	PreviousYesBidDollars string `json:"previous_yes_bid_dollars"`
	// Price level structure for this market, defining price ranges and tick sizes
	PriceLevelStructure string `json:"price_level_structure"`
	// Valid price ranges for orders on this market
	PriceRanges           []PriceRange `json:"price_ranges"`
	PrimaryParticipantKey *string      `json:"primary_participant_key,omitempty"`
	// DEPRECATED: Use price_level_structure and price_ranges instead.
	// Deprecated.
	ResponsePriceUnits string       `json:"response_price_units,omitempty"`
	Result             MarketResult `json:"result"`
	// A plain language description of the most important market terms
	RulesPrimary string `json:"rules_primary"`
	// A plain language description of secondary market terms
	RulesSecondary string `json:"rules_secondary"`
	// The amount of time after determination that the market settles
	SettlementTimerSeconds int `json:"settlement_timer_seconds"`
	// Timestamp when the market was settled. Only filled for settled markets
	SettlementTS *string `json:"settlement_ts,omitempty"`
	// The settlement value of the YES/LONG side of the contract in dollars. Only filled after determina...
	SettlementValueDollars *string `json:"settlement_value_dollars,omitempty"`
	// The current status of the market in its lifecycle.
	Status MarketStatus `json:"status"`
	// Strike type defines how the market strike is defined and evaluated
	StrikeType string `json:"strike_type,omitempty"`
	// Deprecated.
	Subtitle string `json:"subtitle,omitempty"`
	// DEPRECATED: Use price_level_structure and price_ranges instead.
	// Deprecated.
	TickSize int    `json:"tick_size,omitempty"`
	Ticker   string `json:"ticker"`
	// Deprecated.
	Title string `json:"title,omitempty"`
	// Time of the last non-trading metadata update.
	UpdatedTime string `json:"updated_time"`
	// String representation of the 24h market volume in contracts
	Volume24hFP string `json:"volume_24h_fp"`
	// String representation of the market volume in contracts
	VolumeFP string `json:"volume_fp"`
	// Price for the lowest YES sell offer on this market in dollars
	YesAskDollars string `json:"yes_ask_dollars"`
	// Total contract size of orders to sell YES at the best ask price (fixed-point count string).
	YesAskSizeFP string `json:"yes_ask_size_fp"`
	// Price for the highest YES buy offer on this market in dollars
	YesBidDollars string `json:"yes_bid_dollars"`
	// Total contract size of orders to buy YES at the best bid price (fixed-point count string).
	YesBidSizeFP string `json:"yes_bid_size_fp"`
	// Shortened title for the yes side of this market
	YesSubTitle string `json:"yes_sub_title"`
}

// CreateMarketInMultivariateEventCollectionResponse is a generated type from the Kalshi OpenAPI spec.
type CreateMarketInMultivariateEventCollectionResponse struct {
	// Event ticker for the created market.
	EventTicker string `json:"event_ticker"`
	// Market payload of the created market.
	Market Market `json:"market,omitempty"`
	// Market ticker for the created market.
	MarketTicker string `json:"market_ticker"`
}

// CreateOrderGroupRequest is a generated type from the Kalshi OpenAPI spec.
type CreateOrderGroupRequest struct {
	// Specifies the maximum number of contracts that can be matched within this group over a rolling 15...
	ContractsLimit int64 `json:"contracts_limit,omitempty"`
	// String representation of the maximum number of contracts that can be matched within this group ov...
	ContractsLimitFP *string `json:"contracts_limit_fp,omitempty"`
	// Optional subaccount number to use for this order group (0 for primary, 1-32 for subaccounts)
	Subaccount int `json:"subaccount,omitempty"`
}

// CreateOrderGroupResponse is a generated type from the Kalshi OpenAPI spec.
type CreateOrderGroupResponse struct {
	// The unique identifier for the created order group
	OrderGroupID string `json:"order_group_id"`
}

// CreateOrderResponse is a generated type from the Kalshi OpenAPI spec.
type CreateOrderResponse struct {
	Order Order `json:"order"`
}

// CreateOrderV2Response is a generated type from the Kalshi OpenAPI spec.
type CreateOrderV2Response struct {
	// Volume-weighted average fee paid per contract for fills resulting from this request. Only present...
	AverageFeePaid string `json:"average_fee_paid,omitempty"`
	// Volume-weighted average fill price. Only present when fill_count > 0.
	AverageFillPrice string `json:"average_fill_price,omitempty"`
	ClientOrderID    string `json:"client_order_id,omitempty"`
	// Number of contracts filled immediately upon placement.
	FillCount string `json:"fill_count"`
	OrderID   string `json:"order_id"`
	// Number of contracts remaining after placement. For IOC orders, this reflects the final state afte...
	RemainingCount string `json:"remaining_count"`
}

// CreateQuoteRequest is a generated type from the Kalshi OpenAPI spec.
type CreateQuoteRequest struct {
	// The bid price for NO contracts, in dollars
	NoBid string `json:"no_bid"`
	// Whether to rest the remainder of the quote after execution
	RestRemainder bool `json:"rest_remainder"`
	// The ID of the RFQ to quote on
	RFQID string `json:"rfq_id"`
	// Optional subaccount number to place the quote under (0 for primary, 1-32 for subaccounts)
	Subaccount int `json:"subaccount,omitempty"`
	// The bid price for YES contracts, in dollars
	YesBid string `json:"yes_bid"`
}

// CreateQuoteResponse is a generated type from the Kalshi OpenAPI spec.
type CreateQuoteResponse struct {
	// The ID of the newly created quote
	ID string `json:"id"`
}

// CreateRFQRequest is a generated type from the Kalshi OpenAPI spec.
type CreateRFQRequest struct {
	// The number of contracts for the RFQ. Whole contracts only. Contracts may be provided via contract...
	Contracts int `json:"contracts,omitempty"`
	// String representation of the number of contracts for the RFQ. Contracts may be provided via contr...
	ContractsFP *string `json:"contracts_fp,omitempty"`
	// The ticker of the market for which to create an RFQ
	MarketTicker string `json:"market_ticker"`
	// Whether to delete existing RFQs as part of this RFQ's creation
	ReplaceExisting bool `json:"replace_existing,omitempty"`
	// Whether to rest the remainder of the RFQ after execution
	RestRemainder bool `json:"rest_remainder"`
	// The subaccount number to create the RFQ for (direct members only; 0 for primary, 1-32 for subacco...
	Subaccount int `json:"subaccount,omitempty"`
	// The subtrader to create the RFQ for (FCM members only)
	SubtraderID string `json:"subtrader_id,omitempty"`
	// DEPRECATED: The target cost for the RFQ in centi-cents. Use target_cost_dollars instead.
	// Deprecated.
	TargetCostCentiCents int64 `json:"target_cost_centi_cents,omitempty"`
	// The target cost for the RFQ in dollars
	TargetCostDollars string `json:"target_cost_dollars,omitempty"`
}

// CreateRFQResponse is a generated type from the Kalshi OpenAPI spec.
type CreateRFQResponse struct {
	// The ID of the newly created RFQ
	ID string `json:"id"`
}

// CreateSubaccountResponse is a generated type from the Kalshi OpenAPI spec.
type CreateSubaccountResponse struct {
	// The sequential number assigned to this subaccount (1-32).
	SubaccountNumber int `json:"subaccount_number"`
}

// DailySchedule is a generated type from the Kalshi OpenAPI spec.
type DailySchedule struct {
	// Closing time in ET (Eastern Time) format HH:MM.
	CloseTime string `json:"close_time"`
	// Opening time in ET (Eastern Time) format HH:MM.
	OpenTime string `json:"open_time"`
}

// DecreaseOrderRequest is a generated type from the Kalshi OpenAPI spec.
type DecreaseOrderRequest struct {
	// Number of contracts to reduce by (whole contracts only). Reduce-by may be provided via reduce_by ...
	ReduceBy int `json:"reduce_by,omitempty"`
	// String representation of the number of contracts to reduce by. Reduce-by may be provided via redu...
	ReduceByFP *string `json:"reduce_by_fp,omitempty"`
	// Number of contracts to reduce to (whole contracts only). Reduce-to may be provided via reduce_to ...
	ReduceTo int `json:"reduce_to,omitempty"`
	// String representation of the number of contracts to reduce to. Reduce-to may be provided via redu...
	ReduceToFP *string `json:"reduce_to_fp,omitempty"`
	// Optional subaccount number to use for this decrease (0 for primary, 1-32 for subaccounts)
	Subaccount int `json:"subaccount,omitempty"`
}

// DecreaseOrderResponse is a generated type from the Kalshi OpenAPI spec.
type DecreaseOrderResponse struct {
	Order Order `json:"order"`
}

// DecreaseOrderV2Request is a generated type from the Kalshi OpenAPI spec.
type DecreaseOrderV2Request struct {
	// String representation of the number of contracts to reduce to.
	ReduceTo string `json:"reduce_to"`
}

// DecreaseOrderV2Response is a generated type from the Kalshi OpenAPI spec.
type DecreaseOrderV2Response struct {
	ClientOrderID string `json:"client_order_id,omitempty"`
	OrderID       string `json:"order_id"`
	// Number of contracts remaining after the decrease.
	RemainingCount string `json:"remaining_count"`
}

// EmptyResponse An empty response body
type EmptyResponse struct {
}

// EndpointTokenCost is a generated type from the Kalshi OpenAPI spec.
type EndpointTokenCost struct {
	// Configured token cost for an endpoint whose cost differs from the default cost.
	Cost int `json:"cost"`
	// HTTP method for the endpoint.
	Method string `json:"method"`
	// API route path for the endpoint.
	Path string `json:"path"`
}

// EventData is a generated type from the Kalshi OpenAPI spec.
type EventData struct {
	// Whether this event is available to trade on brokers.
	AvailableOnBrokers bool `json:"available_on_brokers"`
	// Event category (deprecated, use series-level category instead).
	// Deprecated.
	Category string `json:"category,omitempty"`
	// Specifies how collateral is returned when markets settle (e.g., 'binary' for standard yes/no mark...
	CollateralReturnType string `json:"collateral_return_type"`
	// Unique identifier for this event.
	EventTicker string `json:"event_ticker"`
	// Timestamp of when this event's metadata was last updated.
	LastUpdatedTS string `json:"last_updated_ts,omitempty"`
	// Array of markets associated with this event. Only populated when 'with_nested_markets=true' is sp...
	Markets []Market `json:"markets,omitempty"`
	// If true, only one market in this event can resolve to 'yes'. If false, multiple markets can resol...
	MutuallyExclusive bool `json:"mutually_exclusive"`
	// Additional metadata for the event.
	ProductMetadata map[string]any `json:"product_metadata"`
	// Unique identifier for the series this event belongs to.
	SeriesTicker string `json:"series_ticker"`
	// The specific date this event is based on. Only filled when the event uses a date strike (mutually...
	StrikeDate *string `json:"strike_date,omitempty"`
	// The time period this event covers (e.g., 'week', 'month'). Only filled when the event uses a peri...
	StrikePeriod *string `json:"strike_period,omitempty"`
	// Shortened descriptive title for the event.
	SubTitle string `json:"sub_title"`
	// Full title of the event.
	Title string `json:"title"`
}

// EventPosition is a generated type from the Kalshi OpenAPI spec.
type EventPosition struct {
	// Cost of the aggregate event position in dollars
	EventExposureDollars string `json:"event_exposure_dollars"`
	// Unique identifier for events
	EventTicker string `json:"event_ticker"`
	// Fees paid on fill orders, in dollars
	FeesPaidDollars string `json:"fees_paid_dollars"`
	// Locked in profit and loss, in dollars
	RealizedPnlDollars string `json:"realized_pnl_dollars"`
	// Total spent on this event in dollars
	TotalCostDollars string `json:"total_cost_dollars"`
	// String representation of the total number of shares traded on this event (including both YES and ...
	TotalCostSharesFP string `json:"total_cost_shares_fp"`
}

// ExchangeStatus is a generated type from the Kalshi OpenAPI spec.
type ExchangeStatus struct {
	// False if the core Kalshi exchange is no longer taking any state changes at all. This includes but...
	ExchangeActive bool `json:"exchange_active"`
	// Estimated downtime for the current exchange maintenance window. However, this is not guaranteed a...
	ExchangeEstimatedResumeTime *string `json:"exchange_estimated_resume_time,omitempty"`
	// True if we are currently permitting trading on the exchange. This is true during trading hours an...
	TradingActive bool `json:"trading_active"`
}

// Fill is a generated type from the Kalshi OpenAPI spec.
type Fill struct {
	// Specifies if this is a buy or sell order
	Action Action `json:"action"`
	// String representation of the number of contracts bought or sold in this fill
	CountFP string `json:"count_fp"`
	// Timestamp when this fill was executed
	CreatedTime string `json:"created_time,omitempty"`
	// Fee cost in fixed-point dollars
	FeeCost string `json:"fee_cost"`
	// Unique identifier for this fill
	FillID string `json:"fill_id"`
	// If true, this fill was a taker (removed liquidity from the order book)
	IsTaker bool `json:"is_taker"`
	// Unique identifier for the market (legacy field name, same as ticker)
	MarketTicker string `json:"market_ticker"`
	// Fill price for the no side in fixed-point dollars
	NoPriceDollars string `json:"no_price_dollars"`
	// Unique identifier for the order that resulted in this fill
	OrderID string `json:"order_id"`
	// Specifies if this is a 'yes' or 'no' fill
	Side Side `json:"side"`
	// Subaccount number (0 for primary, 1-32 for subaccounts). Present for direct users.
	SubaccountNumber *int `json:"subaccount_number,omitempty"`
	// Unique identifier for the market
	Ticker string `json:"ticker"`
	// Unique identifier for this fill (legacy field name, same as fill_id)
	TradeID string `json:"trade_id"`
	// Unix timestamp when this fill was executed (legacy field name)
	TS int64 `json:"ts,omitempty"`
	// Fill price for the yes side in fixed-point dollars
	YesPriceDollars string `json:"yes_price_dollars"`
}

// PercentilePoint is a generated type from the Kalshi OpenAPI spec.
type PercentilePoint struct {
	// The human-readable formatted forecast value.
	FormattedForecast string `json:"formatted_forecast"`
	// The processed numerical forecast value.
	NumericalForecast float64 `json:"numerical_forecast"`
	// The percentile value (0-10000).
	Percentile int `json:"percentile"`
	// The raw numerical forecast value.
	RawNumericalForecast float64 `json:"raw_numerical_forecast"`
}

// ForecastPercentilesPoint is a generated type from the Kalshi OpenAPI spec.
type ForecastPercentilesPoint struct {
	// Unix timestamp for the inclusive end of the forecast period.
	EndPeriodTS int64 `json:"end_period_ts"`
	// The event ticker this forecast is for.
	EventTicker string `json:"event_ticker"`
	// Array of forecast values at different percentiles.
	PercentilePoints []PercentilePoint `json:"percentile_points"`
	// Length of the forecast period in minutes.
	PeriodInterval int `json:"period_interval"`
}

// GenerateApiKeyRequest is a generated type from the Kalshi OpenAPI spec.
type GenerateApiKeyRequest struct {
	// Name for the API key. This helps identify the key's purpose
	Name string `json:"name"`
	// List of scopes to grant to the API key. Valid values are 'read' and 'write'. If 'write' is includ...
	Scopes []string `json:"scopes,omitempty"`
}

// GenerateApiKeyResponse is a generated type from the Kalshi OpenAPI spec.
type GenerateApiKeyResponse struct {
	// Unique identifier for the newly generated API key
	APIKeyID string `json:"api_key_id"`
	// RSA private key in PEM format. This must be stored securely and cannot be retrieved again after t...
	PrivateKey string `json:"private_key"`
}

// GetAccountApiLimitsResponse is a generated type from the Kalshi OpenAPI spec.
type GetAccountApiLimitsResponse struct {
	Read BucketLimit `json:"read"`
	// User's API usage tier.
	UsageTier string      `json:"usage_tier"`
	Write     BucketLimit `json:"write"`
}

// GetAccountEndpointCostsResponse is a generated type from the Kalshi OpenAPI spec.
type GetAccountEndpointCostsResponse struct {
	// Default token cost applied to endpoints that are not listed in `endpoint_costs`. This is currentl...
	DefaultCost int `json:"default_cost"`
	// API v2 endpoints whose configured token cost differs from `default_cost`. Endpoints that use the ...
	EndpointCosts []EndpointTokenCost `json:"endpoint_costs"`
}

// GetApiKeysResponse is a generated type from the Kalshi OpenAPI spec.
type GetApiKeysResponse struct {
	// List of all API keys associated with the user
	APIKeys []ApiKey `json:"api_keys"`
}

// GetBalanceResponse is a generated type from the Kalshi OpenAPI spec.
type GetBalanceResponse struct {
	// Member's available balance in cents. This represents the amount available for trading.
	Balance int64 `json:"balance"`
	// Member's portfolio value in cents. This is the current value of all positions held.
	PortfolioValue int64 `json:"portfolio_value"`
	// Unix timestamp of the last update to the balance.
	UpdatedTS int64 `json:"updated_ts"`
}

// GetCommunicationsIDResponse is a generated type from the Kalshi OpenAPI spec.
type GetCommunicationsIDResponse struct {
	// A public communications ID which is used to identify the user
	CommunicationsID string `json:"communications_id"`
}

// GetEventCandlesticksResponse is a generated type from the Kalshi OpenAPI spec.
type GetEventCandlesticksResponse struct {
	// Adjusted end timestamp if the requested candlesticks would be larger than maxAggregateCandidates.
	AdjustedEndTS int64 `json:"adjusted_end_ts"`
	// Array of market candlestick arrays, one for each market in the event.
	MarketCandlesticks [][]MarketCandlestick `json:"market_candlesticks"`
	// Array of market tickers in the event.
	MarketTickers []string `json:"market_tickers"`
}

// GetEventForecastPercentilesHistoryResponse is a generated type from the Kalshi OpenAPI spec.
type GetEventForecastPercentilesHistoryResponse struct {
	// Array of forecast percentile data points over time.
	ForecastHistory []ForecastPercentilesPoint `json:"forecast_history"`
}

// MarketMetadata is a generated type from the Kalshi OpenAPI spec.
type MarketMetadata struct {
	// The color code for the market.
	ColorCode string `json:"color_code"`
	// A path to an image that represents this market.
	ImageURL string `json:"image_url"`
	// The ticker of the market.
	MarketTicker string `json:"market_ticker"`
}

// SettlementSource is a generated type from the Kalshi OpenAPI spec.
type SettlementSource struct {
	// Name of the settlement source
	Name string `json:"name,omitempty"`
	// URL to the settlement source
	URL string `json:"url,omitempty"`
}

// GetEventMetadataResponse is a generated type from the Kalshi OpenAPI spec.
type GetEventMetadataResponse struct {
	// Event competition.
	Competition *string `json:"competition,omitempty"`
	// Event scope, based on the competition.
	CompetitionScope *string `json:"competition_scope,omitempty"`
	// A path to an image that represents the image of the featured market.
	FeaturedImageURL string `json:"featured_image_url,omitempty"`
	// A path to an image that represents this event.
	ImageURL string `json:"image_url"`
	// Metadata for the markets in this event.
	MarketDetails []MarketMetadata `json:"market_details"`
	// A list of settlement sources for this event.
	SettlementSources []SettlementSource `json:"settlement_sources"`
}

// GetEventResponse is a generated type from the Kalshi OpenAPI spec.
type GetEventResponse struct {
	// Data for the event.
	Event EventData `json:"event"`
	// Data for the markets in this event. This field is deprecated in favour of the "markets" field ins...
	Markets []Market `json:"markets"`
}

// Milestone is a generated type from the Kalshi OpenAPI spec.
type Milestone struct {
	// Category of the milestone. E.g. Sports, Elections, Esports, Crypto.
	Category string `json:"category"`
	// Additional details about the milestone.
	Details map[string]any `json:"details"`
	// End date of the milestone, if any.
	EndDate *string `json:"end_date,omitempty"`
	// Unique identifier for the milestone.
	ID string `json:"id"`
	// Last time this structured target was updated.
	LastUpdatedTS string `json:"last_updated_ts"`
	// Notification message for the milestone.
	NotificationMessage string `json:"notification_message"`
	// List of event tickers directly related to the outcome of this milestone.
	PrimaryEventTickers []string `json:"primary_event_tickers"`
	// List of event tickers related to this milestone.
	RelatedEventTickers []string `json:"related_event_tickers"`
	// Source id of milestone if available.
	SourceID *string `json:"source_id,omitempty"`
	// Source ids of milestone if available.
	SourceIds map[string]any `json:"source_ids,omitempty"`
	// Start date of the milestone.
	StartDate string `json:"start_date"`
	// Title of the milestone.
	Title string `json:"title"`
	// Type of the milestone. E.g. football_game, basketball_game, soccer_tournament_multi_leg, baseball...
	Type string `json:"type"`
}

// GetEventsResponse is a generated type from the Kalshi OpenAPI spec.
type GetEventsResponse struct {
	// Pagination cursor for the next page. Empty if there are no more results.
	Cursor string `json:"cursor"`
	// Array of events matching the query criteria.
	Events []EventData `json:"events"`
	// Array of milestones related to the events.
	Milestones []Milestone `json:"milestones,omitempty"`
}

// GetExchangeAnnouncementsResponse is a generated type from the Kalshi OpenAPI spec.
type GetExchangeAnnouncementsResponse struct {
	// A list of exchange-wide announcements.
	Announcements []Announcement `json:"announcements"`
}

// MaintenanceWindow is a generated type from the Kalshi OpenAPI spec.
type MaintenanceWindow struct {
	// End date and time of the maintenance window.
	EndDatetime string `json:"end_datetime"`
	// Start date and time of the maintenance window.
	StartDatetime string `json:"start_datetime"`
}

// WeeklySchedule is a generated type from the Kalshi OpenAPI spec.
type WeeklySchedule struct {
	// End date and time for when this weekly schedule is no longer effective.
	EndTime string `json:"end_time"`
	// Trading hours for Friday. May contain multiple sessions.
	Friday []DailySchedule `json:"friday"`
	// Trading hours for Monday. May contain multiple sessions.
	Monday []DailySchedule `json:"monday"`
	// Trading hours for Saturday. May contain multiple sessions.
	Saturday []DailySchedule `json:"saturday"`
	// Start date and time for when this weekly schedule is effective.
	StartTime string `json:"start_time"`
	// Trading hours for Sunday. May contain multiple sessions.
	Sunday []DailySchedule `json:"sunday"`
	// Trading hours for Thursday. May contain multiple sessions.
	Thursday []DailySchedule `json:"thursday"`
	// Trading hours for Tuesday. May contain multiple sessions.
	Tuesday []DailySchedule `json:"tuesday"`
	// Trading hours for Wednesday. May contain multiple sessions.
	Wednesday []DailySchedule `json:"wednesday"`
}

// Schedule is a generated type from the Kalshi OpenAPI spec.
type Schedule struct {
	// Scheduled maintenance windows, during which the exchange may be unavailable.
	MaintenanceWindows []MaintenanceWindow `json:"maintenance_windows"`
	// The standard operating hours of the exchange. All times are expressed in ET. Outside of these tim...
	StandardHours []WeeklySchedule `json:"standard_hours"`
}

// GetExchangeScheduleResponse is a generated type from the Kalshi OpenAPI spec.
type GetExchangeScheduleResponse struct {
	Schedule Schedule `json:"schedule"`
}

// GetFillsResponse is a generated type from the Kalshi OpenAPI spec.
type GetFillsResponse struct {
	Cursor string `json:"cursor"`
	Fills  []Fill `json:"fills"`
}

// GetFiltersBySportsResponse is a generated type from the Kalshi OpenAPI spec.
type GetFiltersBySportsResponse struct {
	// Mapping of sports to their filter details
	FiltersBySports map[string]any `json:"filters_by_sports"`
	// Ordered list of sports for display
	SportOrdering []string `json:"sport_ordering"`
}

// PlayByPlay Play-by-play data organized by period.
type PlayByPlay struct {
	Periods []map[string]any `json:"periods,omitempty"`
}

// GetGameStatsResponse is a generated type from the Kalshi OpenAPI spec.
type GetGameStatsResponse struct {
	Pbp PlayByPlay `json:"pbp,omitempty"`
}

// GetHistoricalCutoffResponse is a generated type from the Kalshi OpenAPI spec.
type GetHistoricalCutoffResponse struct {
	// Cutoff based on **market settlement time**. Markets and their candlesticks that settled before th...
	MarketSettledTS string `json:"market_settled_ts"`
	// Cutoff based on **order cancellation or execution time**. Orders canceled or fully executed befor...
	OrdersUpdatedTS string `json:"orders_updated_ts"`
	// Cutoff based on **trade fill time**. Fills that occurred before this timestamp must be accessed v...
	TradesCreatedTS string `json:"trades_created_ts"`
}

// IncentiveProgram is a generated type from the Kalshi OpenAPI spec.
type IncentiveProgram struct {
	// Discount factor in basis points (optional)
	DiscountFactorBps *int `json:"discount_factor_bps,omitempty"`
	// End date of the incentive program
	EndDate string `json:"end_date"`
	// Unique identifier for the incentive program
	ID string `json:"id"`
	// Plain text description of the incentive program
	IncentiveDescription string `json:"incentive_description"`
	// Type of incentive program
	IncentiveType string `json:"incentive_type"`
	// The unique identifier of the market associated with this incentive program
	MarketID string `json:"market_id"`
	// The ticker symbol of the market associated with this incentive program
	MarketTicker string `json:"market_ticker"`
	// Whether the incentive has been paid out
	PaidOut bool `json:"paid_out"`
	// Total reward for the period in centi-cents
	PeriodReward int64 `json:"period_reward"`
	// Start date of the incentive program
	StartDate string `json:"start_date"`
	// String representation of the target size for the incentive program (optional)
	TargetSizeFP *string `json:"target_size_fp,omitempty"`
}

// GetIncentiveProgramsResponse is a generated type from the Kalshi OpenAPI spec.
type GetIncentiveProgramsResponse struct {
	IncentivePrograms []IncentiveProgram `json:"incentive_programs"`
	// Cursor for pagination to get the next page of results
	NextCursor string `json:"next_cursor,omitempty"`
}

// LiveData is a generated type from the Kalshi OpenAPI spec.
type LiveData struct {
	// Live data details as a flexible object
	Details map[string]any `json:"details"`
	// Milestone ID
	MilestoneID string `json:"milestone_id"`
	// Type of live data
	Type string `json:"type"`
}

// GetLiveDataResponse is a generated type from the Kalshi OpenAPI spec.
type GetLiveDataResponse struct {
	LiveData LiveData `json:"live_data"`
}

// GetLiveDatasResponse is a generated type from the Kalshi OpenAPI spec.
type GetLiveDatasResponse struct {
	LiveDatas []LiveData `json:"live_datas"`
}

// PriceDistributionHistorical is a generated type from the Kalshi OpenAPI spec.
type PriceDistributionHistorical struct {
	// Price of the last trade during the candlestick period (in dollars). Null if no trades occurred.
	Close *string `json:"close"`
	// Highest trade price during the candlestick period (in dollars). Null if no trades occurred.
	High *string `json:"high"`
	// Lowest trade price during the candlestick period (in dollars). Null if no trades occurred.
	Low *string `json:"low"`
	// Volume-weighted average price during the candlestick period (in dollars). Null if no trades occur...
	Mean *string `json:"mean"`
	// Price of the first trade during the candlestick period (in dollars). Null if no trades occurred.
	Open *string `json:"open"`
	// Close price from the previous candlestick period (in dollars). Null if this is the first candlest...
	Previous *string `json:"previous"`
}

// MarketCandlestickHistorical is a generated type from the Kalshi OpenAPI spec.
type MarketCandlestickHistorical struct {
	// Unix timestamp for the inclusive end of the candlestick period.
	EndPeriodTS int64 `json:"end_period_ts"`
	// String representation of the number of contracts bought on the market by end of the candlestick p...
	OpenInterest string `json:"open_interest"`
	// Open, high, low, close (OHLC) and more data for trade YES contract prices on the market during th...
	Price PriceDistributionHistorical `json:"price"`
	// String representation of the number of contracts bought on the market during the candlestick period.
	Volume string `json:"volume"`
	// Open, high, low, close (OHLC) data for YES sell offers on the market during the candlestick period.
	YesAsk BidAskDistributionHistorical `json:"yes_ask"`
	// Open, high, low, close (OHLC) data for YES buy offers on the market during the candlestick period.
	YesBid BidAskDistributionHistorical `json:"yes_bid"`
}

// GetMarketCandlesticksHistoricalResponse is a generated type from the Kalshi OpenAPI spec.
type GetMarketCandlesticksHistoricalResponse struct {
	// Array of candlestick data points for the specified time range.
	Candlesticks []MarketCandlestickHistorical `json:"candlesticks"`
	// Unique identifier for the market.
	Ticker string `json:"ticker"`
}

// GetMarketCandlesticksResponse is a generated type from the Kalshi OpenAPI spec.
type GetMarketCandlesticksResponse struct {
	// Array of candlestick data points for the specified time range.
	Candlesticks []MarketCandlestick `json:"candlesticks"`
	// Unique identifier for the market.
	Ticker string `json:"ticker"`
}

// PriceLevelDollarsCountFp Price level in dollars represented as [dollars_string, fp] where dollars_string is like "0.1500" and fp is a FixedPointCount string (fixed-point contract count). The second element is the contract quantity (not price).
type PriceLevelDollarsCountFp = []string

// OrderbookCountFp Orderbook with fixed-point contract counts (fp) in all dollar price levels.
type OrderbookCountFp struct {
	NoDollars  []PriceLevelDollarsCountFp `json:"no_dollars"`
	YesDollars []PriceLevelDollarsCountFp `json:"yes_dollars"`
}

// GetMarketOrderbookResponse is a generated type from the Kalshi OpenAPI spec.
type GetMarketOrderbookResponse struct {
	// Orderbook with fixed-point contract counts (fp) in all price levels.
	OrderbookFP OrderbookCountFp `json:"orderbook_fp"`
}

// MarketOrderbookFp is a generated type from the Kalshi OpenAPI spec.
type MarketOrderbookFp struct {
	OrderbookFP OrderbookCountFp `json:"orderbook_fp"`
	Ticker      string           `json:"ticker"`
}

// GetMarketOrderbooksResponse is a generated type from the Kalshi OpenAPI spec.
type GetMarketOrderbooksResponse struct {
	Orderbooks []MarketOrderbookFp `json:"orderbooks"`
}

// GetMarketResponse is a generated type from the Kalshi OpenAPI spec.
type GetMarketResponse struct {
	Market Market `json:"market"`
}

// GetMarketsResponse is a generated type from the Kalshi OpenAPI spec.
type GetMarketsResponse struct {
	Cursor  string   `json:"cursor"`
	Markets []Market `json:"markets"`
}

// GetMilestoneResponse is a generated type from the Kalshi OpenAPI spec.
type GetMilestoneResponse struct {
	// The milestone data.
	Milestone Milestone `json:"milestone"`
}

// GetMilestonesResponse is a generated type from the Kalshi OpenAPI spec.
type GetMilestonesResponse struct {
	// Cursor for pagination.
	Cursor string `json:"cursor,omitempty"`
	// List of milestones.
	Milestones []Milestone `json:"milestones"`
}

// LookupPoint is a generated type from the Kalshi OpenAPI spec.
type LookupPoint struct {
	// Event ticker for the lookup point.
	EventTicker string `json:"event_ticker"`
	// Timestamp when this lookup was last queried.
	LastQueriedTS string `json:"last_queried_ts"`
	// Market ticker for the lookup point.
	MarketTicker string `json:"market_ticker"`
	// Markets that were selected for this lookup.
	SelectedMarkets []TickerPair `json:"selected_markets"`
}

// GetMultivariateEventCollectionLookupHistoryResponse is a generated type from the Kalshi OpenAPI spec.
type GetMultivariateEventCollectionLookupHistoryResponse struct {
	// List of recent lookup points in the collection.
	LookupPoints []LookupPoint `json:"lookup_points"`
}

// MultivariateEventCollection is a generated type from the Kalshi OpenAPI spec.
type MultivariateEventCollection struct {
	// [DEPRECATED - Use associated_events instead] A list of events associated with the collection. Mar...
	AssociatedEventTickers []string `json:"associated_event_tickers"`
	// List of events with their individual configuration.
	AssociatedEvents []AssociatedEvent `json:"associated_events"`
	// The close date of the collection. After this time, the collection cannot be interacted with.
	CloseDate string `json:"close_date"`
	// Unique identifier for the collection.
	CollectionTicker string `json:"collection_ticker"`
	// Short description of the collection.
	Description string `json:"description"`
	// A functional description of the collection describing how inputs affect the output.
	FunctionalDescription string `json:"functional_description"`
	// [DEPRECATED - Use associated_events instead] Whether the collection requires that only the market...
	IsAllYes bool `json:"is_all_yes"`
	// Whether the collection is ordered. If true, the order of markets passed into Lookup/Create affect...
	IsOrdered bool `json:"is_ordered"`
	// [DEPRECATED - Use associated_events instead] Whether the collection accepts multiple markets from...
	IsSingleMarketPerEvent bool `json:"is_single_market_per_event"`
	// The open date of the collection. Before this time, the collection cannot be interacted with.
	OpenDate string `json:"open_date"`
	// Series associated with the collection. Events produced in the collection will be associated with ...
	SeriesTicker string `json:"series_ticker"`
	// The maximum number of markets that must be passed into Lookup/Create (inclusive).
	SizeMax int `json:"size_max"`
	// The minimum number of markets that must be passed into Lookup/Create (inclusive).
	SizeMin int `json:"size_min"`
	// Title of the collection.
	Title string `json:"title"`
}

// GetMultivariateEventCollectionResponse is a generated type from the Kalshi OpenAPI spec.
type GetMultivariateEventCollectionResponse struct {
	// The multivariate event collection.
	MultivariateContract MultivariateEventCollection `json:"multivariate_contract"`
}

// GetMultivariateEventCollectionsResponse is a generated type from the Kalshi OpenAPI spec.
type GetMultivariateEventCollectionsResponse struct {
	// The Cursor represents a pointer to the next page of records in the pagination. Use the value retu...
	Cursor string `json:"cursor,omitempty"`
	// List of multivariate event collections.
	MultivariateContracts []MultivariateEventCollection `json:"multivariate_contracts"`
}

// GetMultivariateEventsResponse is a generated type from the Kalshi OpenAPI spec.
type GetMultivariateEventsResponse struct {
	// Pagination cursor for the next page. Empty if there are no more results.
	Cursor string `json:"cursor"`
	// Array of multivariate events matching the query criteria.
	Events []EventData `json:"events"`
}

// GetOrderGroupResponse is a generated type from the Kalshi OpenAPI spec.
type GetOrderGroupResponse struct {
	// String representation of the current maximum contracts allowed over a rolling 15-second window.
	ContractsLimitFP string `json:"contracts_limit_fp,omitempty"`
	// Whether auto-cancel is enabled for this order group
	IsAutoCancelEnabled bool `json:"is_auto_cancel_enabled"`
	// List of order IDs that belong to this order group
	Orders []string `json:"orders"`
}

// OrderGroup is a generated type from the Kalshi OpenAPI spec.
type OrderGroup struct {
	// String representation of the current maximum contracts allowed over a rolling 15-second window.
	ContractsLimitFP string `json:"contracts_limit_fp,omitempty"`
	// Unique identifier for the order group
	ID string `json:"id"`
	// Whether auto-cancel is enabled for this order group
	IsAutoCancelEnabled bool `json:"is_auto_cancel_enabled"`
}

// GetOrderGroupsResponse is a generated type from the Kalshi OpenAPI spec.
type GetOrderGroupsResponse struct {
	OrderGroups []OrderGroup `json:"order_groups,omitempty"`
}

// GetOrderQueuePositionResponse is a generated type from the Kalshi OpenAPI spec.
type GetOrderQueuePositionResponse struct {
	// The number of preceding shares before the order in the queue.
	QueuePositionFP string `json:"queue_position_fp"`
}

// OrderQueuePosition is a generated type from the Kalshi OpenAPI spec.
type OrderQueuePosition struct {
	// The market ticker
	MarketTicker string `json:"market_ticker"`
	// The order ID
	OrderID string `json:"order_id"`
	// The number of preceding shares before the order in the queue.
	QueuePositionFP string `json:"queue_position_fp"`
}

// GetOrderQueuePositionsResponse is a generated type from the Kalshi OpenAPI spec.
type GetOrderQueuePositionsResponse struct {
	// Queue positions for all matching orders
	QueuePositions []OrderQueuePosition `json:"queue_positions"`
}

// GetOrderResponse is a generated type from the Kalshi OpenAPI spec.
type GetOrderResponse struct {
	Order Order `json:"order"`
}

// GetOrdersResponse is a generated type from the Kalshi OpenAPI spec.
type GetOrdersResponse struct {
	Cursor string  `json:"cursor"`
	Orders []Order `json:"orders"`
}

// GetPortfolioRestingOrderTotalValueResponse is a generated type from the Kalshi OpenAPI spec.
type GetPortfolioRestingOrderTotalValueResponse struct {
	// Total value of resting orders in cents
	TotalRestingOrderValue int `json:"total_resting_order_value"`
}

// MarketPosition is a generated type from the Kalshi OpenAPI spec.
type MarketPosition struct {
	// Fees paid on fill orders, in dollars
	FeesPaidDollars string `json:"fees_paid_dollars"`
	// Last time the position is updated
	LastUpdatedTS string `json:"last_updated_ts"`
	// Cost of the aggregate market position in dollars
	MarketExposureDollars string `json:"market_exposure_dollars"`
	// String representation of the number of contracts bought in this market. Negative means NO contrac...
	PositionFP string `json:"position_fp"`
	// Locked in profit and loss, in dollars
	RealizedPnlDollars string `json:"realized_pnl_dollars"`
	// [DEPRECATED] Aggregate size of resting orders in contract units
	// Deprecated.
	RestingOrdersCount int `json:"resting_orders_count"`
	// Unique identifier for the market
	Ticker string `json:"ticker"`
	// Total spent on this market in dollars
	TotalTradedDollars string `json:"total_traded_dollars"`
}

// GetPositionsResponse is a generated type from the Kalshi OpenAPI spec.
type GetPositionsResponse struct {
	// The Cursor represents a pointer to the next page of records in the pagination. Use the value retu...
	Cursor string `json:"cursor,omitempty"`
	// List of event positions
	EventPositions []EventPosition `json:"event_positions"`
	// List of market positions
	MarketPositions []MarketPosition `json:"market_positions"`
}

// Quote is a generated type from the Kalshi OpenAPI spec.
type Quote struct {
	// The side that was accepted (yes or no)
	AcceptedSide string `json:"accepted_side,omitempty"`
	// Timestamp when the quote was accepted
	AcceptedTS string `json:"accepted_ts,omitempty"`
	// Reason for quote cancellation if cancelled
	CancellationReason string `json:"cancellation_reason,omitempty"`
	// Timestamp when the quote was cancelled
	CancelledTS string `json:"cancelled_ts,omitempty"`
	// Timestamp when the quote was confirmed
	ConfirmedTS string `json:"confirmed_ts,omitempty"`
	// String representation of the number of contracts in the quote
	ContractsFP string `json:"contracts_fp"`
	// Timestamp when the quote was created
	CreatedTS string `json:"created_ts"`
	// Public communications ID of the quote creator
	CreatorID string `json:"creator_id"`
	// Order ID for the quote creator (private field)
	CreatorOrderID string `json:"creator_order_id,omitempty"`
	// Subaccount number of the quote creator (visible when the caller is the quote creator)
	CreatorSubaccount int `json:"creator_subaccount,omitempty"`
	// User ID of the quote creator (private field)
	CreatorUserID string `json:"creator_user_id,omitempty"`
	// Timestamp when the quote was executed
	ExecutedTS string `json:"executed_ts,omitempty"`
	// Unique identifier for the quote
	ID string `json:"id"`
	// The ticker of the market this quote is for
	MarketTicker string `json:"market_ticker"`
	// Bid price for NO contracts, in dollars
	NoBidDollars string `json:"no_bid_dollars"`
	// Number of NO contracts offered in the quote (fixed-point)
	NoContractsFP string `json:"no_contracts_fp,omitempty"`
	// Whether to rest the remainder of the quote after execution
	RestRemainder bool `json:"rest_remainder,omitempty"`
	// Public communications ID of the RFQ creator
	RFQCreatorID string `json:"rfq_creator_id"`
	// Order ID for the RFQ creator (private field)
	RFQCreatorOrderID string `json:"rfq_creator_order_id,omitempty"`
	// Subaccount number of the RFQ creator (visible when the caller is the RFQ creator)
	RFQCreatorSubaccount int `json:"rfq_creator_subaccount,omitempty"`
	// User ID of the RFQ creator (private field)
	RFQCreatorUserID string `json:"rfq_creator_user_id,omitempty"`
	// ID of the RFQ this quote is responding to
	RFQID string `json:"rfq_id"`
	// Total value requested in the RFQ in dollars
	RFQTargetCostDollars string `json:"rfq_target_cost_dollars,omitempty"`
	// Current status of the quote
	Status string `json:"status"`
	// Timestamp when the quote was last updated
	UpdatedTS string `json:"updated_ts"`
	// Bid price for YES contracts, in dollars
	YesBidDollars string `json:"yes_bid_dollars"`
	// Number of YES contracts offered in the quote (fixed-point)
	YesContractsFP string `json:"yes_contracts_fp,omitempty"`
}

// GetQuoteResponse is a generated type from the Kalshi OpenAPI spec.
type GetQuoteResponse struct {
	// The details of the requested quote
	Quote Quote `json:"quote"`
}

// GetQuotesResponse is a generated type from the Kalshi OpenAPI spec.
type GetQuotesResponse struct {
	// Cursor for pagination to get the next page of results
	Cursor string `json:"cursor,omitempty"`
	// List of quotes matching the query criteria
	Quotes []Quote `json:"quotes"`
}

// RFQ is a generated type from the Kalshi OpenAPI spec.
type RFQ struct {
	// Reason for RFQ cancellation if cancelled
	CancellationReason string `json:"cancellation_reason,omitempty"`
	// Timestamp when the RFQ was cancelled
	CancelledTS string `json:"cancelled_ts,omitempty"`
	// String representation of the number of contracts requested in the RFQ
	ContractsFP string `json:"contracts_fp"`
	// Timestamp when the RFQ was created
	CreatedTS string `json:"created_ts"`
	// Public communications ID of the RFQ creator.
	CreatorID string `json:"creator_id"`
	// Subaccount number of the RFQ creator (visible when the caller is the RFQ creator)
	CreatorSubaccount int `json:"creator_subaccount,omitempty"`
	// User ID of the RFQ creator (private field)
	CreatorUserID string `json:"creator_user_id,omitempty"`
	// Unique identifier for the RFQ
	ID string `json:"id"`
	// The ticker of the market this RFQ is for
	MarketTicker string `json:"market_ticker"`
	// Ticker of the MVE collection this market belongs to
	MVECollectionTicker string `json:"mve_collection_ticker,omitempty"`
	// Selected legs for the MVE collection
	MVESelectedLegs []MveSelectedLeg `json:"mve_selected_legs,omitempty"`
	// Whether to rest the remainder of the RFQ after execution
	RestRemainder bool `json:"rest_remainder,omitempty"`
	// Current status of the RFQ (open, closed)
	Status string `json:"status"`
	// Total value of the RFQ in dollars
	TargetCostDollars string `json:"target_cost_dollars,omitempty"`
	// Timestamp when the RFQ was last updated
	UpdatedTS string `json:"updated_ts,omitempty"`
}

// GetRFQResponse is a generated type from the Kalshi OpenAPI spec.
type GetRFQResponse struct {
	// The details of the requested RFQ
	RFQ RFQ `json:"rfq"`
}

// GetRFQsResponse is a generated type from the Kalshi OpenAPI spec.
type GetRFQsResponse struct {
	// Cursor for pagination to get the next page of results
	Cursor string `json:"cursor,omitempty"`
	// List of RFQs matching the query criteria
	Rfqs []RFQ `json:"rfqs"`
}

// SeriesFeeChange is a generated type from the Kalshi OpenAPI spec.
type SeriesFeeChange struct {
	// New fee multiplier for the series
	FeeMultiplier float64 `json:"fee_multiplier"`
	// New fee type for the series
	FeeType string `json:"fee_type"`
	// Unique identifier for this fee change
	ID string `json:"id"`
	// Timestamp when this fee change is scheduled to take effect
	ScheduledTS string `json:"scheduled_ts"`
	// Series ticker this fee change applies to
	SeriesTicker string `json:"series_ticker"`
}

// GetSeriesFeeChangesResponse is a generated type from the Kalshi OpenAPI spec.
type GetSeriesFeeChangesResponse struct {
	SeriesFeeChangeArr []SeriesFeeChange `json:"series_fee_change_arr"`
}

// Series is a generated type from the Kalshi OpenAPI spec.
type Series struct {
	// AdditionalProhibitions is a list of additional trading prohibitions for this series.
	AdditionalProhibitions []string `json:"additional_prohibitions"`
	// Category specifies the category which this series belongs to.
	Category string `json:"category"`
	// ContractTermsUrl is the URL to the current terms of the contract underlying the series.
	ContractTermsURL *string `json:"contract_terms_url"`
	// ContractUrl provides a direct link to the original filing of the contract which underlies the ser...
	ContractURL *string `json:"contract_url"`
	// FeeMultiplier is a floating point multiplier applied to the fee calculations.
	FeeMultiplier float64 `json:"fee_multiplier"`
	// FeeType is a string representing the series' fee structure. Fee structures can be found at https:...
	FeeType string `json:"fee_type"`
	// Description of the frequency of the series. There is no fixed value set here, but will be somethi...
	Frequency string `json:"frequency"`
	// Timestamp of when this series' metadata was last updated.
	LastUpdatedTS string `json:"last_updated_ts,omitempty"`
	// Internal product metadata of the series.
	ProductMetadata map[string]any `json:"product_metadata,omitempty"`
	// SettlementSources specifies the official sources used for the determination of markets within the...
	SettlementSources []SettlementSource `json:"settlement_sources"`
	// Tags specifies the subjects that this series relates to, multiple series from different categorie...
	Tags []string `json:"tags"`
	// Ticker that identifies this series.
	Ticker string `json:"ticker"`
	// Title describing the series. For full context use you should use this field with the title field ...
	Title string `json:"title"`
	// String representation of the total number of contracts traded across all events in this series.
	VolumeFP string `json:"volume_fp,omitempty"`
}

// GetSeriesListResponse is a generated type from the Kalshi OpenAPI spec.
type GetSeriesListResponse struct {
	Series []Series `json:"series"`
}

// GetSeriesResponse is a generated type from the Kalshi OpenAPI spec.
type GetSeriesResponse struct {
	Series Series `json:"series"`
}

// Settlement is a generated type from the Kalshi OpenAPI spec.
type Settlement struct {
	// The event ticker symbol of the market that was settled.
	EventTicker string `json:"event_ticker"`
	// Total fees paid in fixed point dollars.
	FeeCost string `json:"fee_cost"`
	// The outcome of the market settlement. 'yes' = market resolved to YES, 'no' = market resolved to N...
	MarketResult string `json:"market_result"`
	// String representation of the number of NO contracts owned at the time of settlement.
	NoCountFP string `json:"no_count_fp"`
	// Total cost basis of all NO contracts in fixed-point dollars.
	NoTotalCostDollars string `json:"no_total_cost_dollars"`
	// Total revenue earned from this settlement in cents (winning contracts pay out 100 cents each).
	Revenue int `json:"revenue"`
	// Timestamp when the market was settled and payouts were processed.
	SettledTime string `json:"settled_time"`
	// The ticker symbol of the market that was settled.
	Ticker string `json:"ticker"`
	// Payout of a single yes contract in cents.
	Value *int `json:"value,omitempty"`
	// String representation of the number of YES contracts owned at the time of settlement.
	YesCountFP string `json:"yes_count_fp"`
	// Total cost basis of all YES contracts in fixed-point dollars.
	YesTotalCostDollars string `json:"yes_total_cost_dollars"`
}

// GetSettlementsResponse is a generated type from the Kalshi OpenAPI spec.
type GetSettlementsResponse struct {
	Cursor      string       `json:"cursor,omitempty"`
	Settlements []Settlement `json:"settlements"`
}

// StructuredTarget is a generated type from the Kalshi OpenAPI spec.
type StructuredTarget struct {
	// Additional details about the structured target. Contains flexible JSON data specific to the targe...
	Details map[string]any `json:"details,omitempty"`
	// Unique identifier for the structured target.
	ID string `json:"id,omitempty"`
	// Timestamp when this structured target was last updated.
	LastUpdatedTS string `json:"last_updated_ts,omitempty"`
	// Name of the structured target.
	Name string `json:"name,omitempty"`
	// External source identifier for the structured target, if available (e.g., third-party data provid...
	SourceID string `json:"source_id,omitempty"`
	// Source ids of structured target if available.
	SourceIds map[string]any `json:"source_ids,omitempty"`
	// Type of the structured target.
	Type string `json:"type,omitempty"`
}

// GetStructuredTargetResponse is a generated type from the Kalshi OpenAPI spec.
type GetStructuredTargetResponse struct {
	StructuredTarget StructuredTarget `json:"structured_target,omitempty"`
}

// GetStructuredTargetsResponse is a generated type from the Kalshi OpenAPI spec.
type GetStructuredTargetsResponse struct {
	// Pagination cursor for the next page. Empty if there are no more results.
	Cursor            string             `json:"cursor,omitempty"`
	StructuredTargets []StructuredTarget `json:"structured_targets,omitempty"`
}

// GetSubaccountBalancesResponse is a generated type from the Kalshi OpenAPI spec.
type GetSubaccountBalancesResponse struct {
	SubaccountBalances []any `json:"subaccount_balances"`
}

// GetSubaccountNettingResponse is a generated type from the Kalshi OpenAPI spec.
type GetSubaccountNettingResponse struct {
	NettingConfigs []any `json:"netting_configs"`
}

// GetSubaccountTransfersResponse is a generated type from the Kalshi OpenAPI spec.
type GetSubaccountTransfersResponse struct {
	// Cursor for the next page of results.
	Cursor    string `json:"cursor,omitempty"`
	Transfers []any  `json:"transfers"`
}

// GetTagsForSeriesCategoriesResponse is a generated type from the Kalshi OpenAPI spec.
type GetTagsForSeriesCategoriesResponse struct {
	// Mapping of series categories to their associated tags
	TagsByCategories map[string]any `json:"tags_by_categories"`
}

// Trade is a generated type from the Kalshi OpenAPI spec.
type Trade struct {
	// String representation of the number of contracts bought or sold in this trade
	CountFP string `json:"count_fp"`
	// Timestamp when this trade was executed
	CreatedTime string `json:"created_time"`
	// No price for this trade in dollars
	NoPriceDollars string `json:"no_price_dollars"`
	// Side for the taker of this trade
	TakerSide Side `json:"taker_side"`
	// Unique identifier for the market
	Ticker string `json:"ticker"`
	// Unique identifier for this trade
	TradeID string `json:"trade_id"`
	// Yes price for this trade in dollars
	YesPriceDollars string `json:"yes_price_dollars"`
}

// GetTradesResponse is a generated type from the Kalshi OpenAPI spec.
type GetTradesResponse struct {
	Cursor string  `json:"cursor"`
	Trades []Trade `json:"trades"`
}

// GetUserDataTimestampResponse is a generated type from the Kalshi OpenAPI spec.
type GetUserDataTimestampResponse struct {
	// Timestamp when user data was last updated.
	AsOfTime string `json:"as_of_time"`
}

// LookupTickersForMarketInMultivariateEventCollectionRequest is a generated type from the Kalshi OpenAPI spec.
type LookupTickersForMarketInMultivariateEventCollectionRequest struct {
	// List of selected markets that act as parameters to determine which market is produced.
	SelectedMarkets []TickerPair `json:"selected_markets"`
}

// LookupTickersForMarketInMultivariateEventCollectionResponse is a generated type from the Kalshi OpenAPI spec.
type LookupTickersForMarketInMultivariateEventCollectionResponse struct {
	// Event ticker for the looked up market.
	EventTicker string `json:"event_ticker"`
	// Market ticker for the looked up market.
	MarketTicker string `json:"market_ticker"`
}

// ScopeList is a generated type from the Kalshi OpenAPI spec.
type ScopeList struct {
	// List of scopes
	Scopes []string `json:"scopes"`
}

// SportFilterDetails is a generated type from the Kalshi OpenAPI spec.
type SportFilterDetails struct {
	// Mapping of competitions to their scope lists
	Competitions map[string]any `json:"competitions"`
	// List of scopes available for this sport
	Scopes []string `json:"scopes"`
}

// UpdateOrderGroupLimitRequest is a generated type from the Kalshi OpenAPI spec.
type UpdateOrderGroupLimitRequest struct {
	// New maximum number of contracts that can be matched within this group over a rolling 15-second wi...
	ContractsLimit int64 `json:"contracts_limit,omitempty"`
	// String representation of the new maximum number of contracts that can be matched within this grou...
	ContractsLimitFP *string `json:"contracts_limit_fp,omitempty"`
}

// UpdateSubaccountNettingRequest is a generated type from the Kalshi OpenAPI spec.
type UpdateSubaccountNettingRequest struct {
	// Whether netting is enabled for this subaccount.
	Enabled bool `json:"enabled"`
	// Subaccount number (0 for primary, 1-32 for subaccounts).
	SubaccountNumber int `json:"subaccount_number"`
}
