// Code generated by tools/generate_ws_types from https://docs.kalshi.com/asyncapi.yaml — DO NOT EDIT.
// Source: ws_messages_generated.go

package gokalshi

// ---------------------------------------------------------------------------
// Outgoing commands
// ---------------------------------------------------------------------------

// WSCommand is the generic envelope for outgoing WebSocket commands.
// Cmd values: see WSCmd constants.
type WSCommand struct {
	ID     int   `json:"id"`
	Cmd    WSCmd `json:"cmd"`
	Params any   `json:"params,omitempty"` // nil for list_subscriptions
}

// SubscribeParams are the parameters for a "subscribe" command.
type SubscribeParams struct {
	// List of channels to subscribe to
	Channels []string `json:"channels"`
	// cfbenchmarks_value channel only. CF Benchmarks index IDs to seed on the initial subscribe (omit t...
	IndexIds []string `json:"index_ids,omitempty"`
	// Subscribe to a single market by UUID (ticker only; mutually exclusive with market_ids and market_...
	MarketID string `json:"market_id,omitempty"`
	// Subscribe to multiple markets by UUID (ticker only; mutually exclusive with market_id and market_...
	MarketIds []string `json:"market_ids,omitempty"`
	// Subscribe to a single market. Type: string. Example: "KXBTCD-25AUG0517-T114999.99" (mutually excl...
	MarketTicker string `json:"market_ticker,omitempty"`
	// Subscribe to multiple markets. Type: array of strings. Example: ["KXBTCD-25AUG0517-T114999.99", "...
	MarketTickers []string `json:"market_tickers,omitempty"`
	// If true, receive an initial snapshot for requested market tickers on the ticker channel
	SendInitialSnapshot bool `json:"send_initial_snapshot,omitempty"`
	// Number of shards for communications channel fanout (optional)
	ShardFactor int `json:"shard_factor,omitempty"`
	// Shard key for communications channel fanout (requires shard_factor)
	ShardKey int `json:"shard_key,omitempty"`
	// If true, OK responses omit the market_tickers/market_ids lists for this subscription
	SkipTickerAck bool `json:"skip_ticker_ack,omitempty"`
	// Orderbook channel only. When true, no-side `orderbook_delta` and `orderbook_snapshot` updates
	UseYesPrice bool `json:"use_yes_price,omitempty"`
}

// UnsubscribeParams are the parameters for an "unsubscribe" command.
type UnsubscribeParams struct {
	// List of subscription IDs to cancel
	SIDs []int `json:"sids"`
}

// UpdateSubParams are the parameters for an "update_subscription" command.
type UpdateSubParams struct {
	Action WSUpdateAction `json:"action"`
	// CF Benchmarks index IDs to add or remove. Use ["all"] to track every available index. Required fo...
	IndexIds []string `json:"index_ids,omitempty"`
	// Add/remove a single market by UUID (ticker only)
	MarketID string `json:"market_id,omitempty"`
	// Add/remove multiple markets by UUID (ticker only)
	MarketIds []string `json:"market_ids,omitempty"`
	// Add/remove a single market. Type: string
	MarketTicker string `json:"market_ticker,omitempty"`
	// Add/remove multiple markets. Type: array of strings
	MarketTickers []string `json:"market_tickers,omitempty"`
	// If true, receive an initial snapshot for newly added market tickers on the ticker channel
	SendInitialSnapshot bool `json:"send_initial_snapshot,omitempty"`
	// Single subscription ID to update (alternative to sids array)
	SID int `json:"sid,omitempty"`
	// Array containing exactly one subscription ID (alternative to sid). Either sid or sids must be pro...
	SIDs []int `json:"sids,omitempty"`
}

// ---------------------------------------------------------------------------
// Incoming response msg bodies (parsed from WSMessage.Msg)
// ---------------------------------------------------------------------------

// SubscribedBody is the msg body for a "subscribed" response.
type SubscribedBody struct {
	Channel string `json:"channel"`
	SID     int    `json:"sid"`
}

// OkBody is the msg body for an "ok" response.
type OkBody struct {
	// Full list of market IDs after update
	MarketIds []string `json:"market_ids,omitempty"`
	// Full list of market tickers after update
	MarketTickers []string `json:"market_tickers,omitempty"`
}

// WSErrorBody is the msg body for an "error" response.
type WSErrorBody struct {
	// Error code identifying the type of error:
	Code int `json:"code"`
	// Market UUID if error is market-specific (optional)
	MarketID string `json:"market_id,omitempty"`
	// Market ticker if error is market-specific (optional)
	MarketTicker string `json:"market_ticker,omitempty"`
	// Human-readable error message
	Msg string `json:"msg"`
}

// ---------------------------------------------------------------------------
// WS error codes (from Kalshi API spec)
// ---------------------------------------------------------------------------

const (
	WSErrUnableToProcess     = 1
	WSErrParamsRequired      = 2
	WSErrChannelsRequired    = 3
	WSErrSIDsRequired        = 4
	WSErrUnknownCommand      = 5
	WSErrAlreadySubscribed   = 6
	WSErrUnknownSID          = 7
	WSErrUnknownChannel      = 8
	WSErrAuthRequired        = 9
	WSErrChannelError        = 10
	WSErrInvalidParam        = 11
	WSErrExactlyOneSID       = 12
	WSErrUnsupportedAction   = 13
	WSErrMarketTickerReq     = 14
	WSErrActionRequired      = 15
	WSErrMarketNotFound      = 16
	WSErrInternal            = 17
	WSErrCommandTimeout      = 18
	WSErrShardFactorPositive = 19
	WSErrShardFactorRequired = 20
	WSErrShardKeyRange       = 21
	WSErrShardFactorTooLarge = 22
	WSErrMatchIDsRequired    = 23
	WSErrIndexIDsRequired    = 24
	WSErrSubBufferOverflow   = 25
)

// ---------------------------------------------------------------------------
// Shared sub-types
// ---------------------------------------------------------------------------

// CfbenchmarksAvgData Windowed-average metadata for a CF Benchmarks index value.
type CfbenchmarksAvgData struct {
	// Average value over the window, formatted to 8 decimal places
	Value string `json:"value"`
	// Window end boundary, exclusive (unix ms)
	WindowEndTSExclusive int `json:"window_end_ts_exclusive"`
	// Number of ticks counted in the window
	WindowSize int `json:"window_size"`
	// Window start boundary (unix ms)
	WindowStartTSMs int `json:"window_start_ts_ms"`
}

// ---------------------------------------------------------------------------
// Inline sub-types
// ---------------------------------------------------------------------------

// MarketLifecycleAdditionalMetadata is a nested object type within a WS data message.
type MarketLifecycleAdditionalMetadata struct {
	CanCloseEarly        bool           `json:"can_close_early,omitempty"`
	CapStrike            float64        `json:"cap_strike,omitempty"`
	CustomStrike         map[string]any `json:"custom_strike,omitempty"`
	EventTicker          string         `json:"event_ticker,omitempty"`
	ExpectedExpirationTS int64          `json:"expected_expiration_ts,omitempty"`
	FloorStrike          float64        `json:"floor_strike,omitempty"`
	Name                 string         `json:"name,omitempty"`
	NoSubTitle           string         `json:"no_sub_title,omitempty"`
	RulesPrimary         string         `json:"rules_primary,omitempty"`
	RulesSecondary       string         `json:"rules_secondary,omitempty"`
	StrikeType           string         `json:"strike_type,omitempty"`
	Title                string         `json:"title,omitempty"`
	YesSubTitle          string         `json:"yes_sub_title,omitempty"`
}

// MultivariateLookupSelectedMarket is a nested object type within a WS data message.
type MultivariateLookupSelectedMarket struct {
	EventTicker  string `json:"event_ticker"`
	MarketTicker string `json:"market_ticker"`
	Side         Side   `json:"side"`
}

// ---------------------------------------------------------------------------
// Incoming channel data messages
// ---------------------------------------------------------------------------

// CfbenchmarksValueData is the msg body for a "cfbenchmarks_value" message.
type CfbenchmarksValueData struct {
	// Trailing 60-second average metadata. The window is per-tick and trailing:
	Avg60sData CfbenchmarksAvgData `json:"avg_60s_data"`
	// The raw CF Benchmarks JSON frame, as a string
	Data string `json:"data"`
	// CF Benchmarks index ID (for example "BRTI")
	IndexID string `json:"index_id"`
	// Optional - present only during the final minute before quarter-hour close (:00, :15, :30, :45).
	Last60sWindowedAverage15min CfbenchmarksAvgData `json:"last_60s_windowed_average_15min,omitempty"`
	// When Kalshi received the upstream frame (unix ms)
	ReceivedAt int `json:"received_at"`
}

// CfbenchmarksValueIndexlistData is the msg body for a "cfbenchmarks_value_indexlist" message.
type CfbenchmarksValueIndexlistData struct {
	// Available CF Benchmarks index IDs
	IndexIds []string `json:"index_ids"`
}

// EventFeeUpdateData is the msg body for a "event_fee_update" message.
type EventFeeUpdateData struct {
	// Unique identifier for the event
	EventTicker string `json:"event_ticker"`
	// Event fee multiplier override. `null` when the override has been cleared.
	FeeMultiplierOverride *float64 `json:"fee_multiplier_override"`
	// Event fee type override. `null` when the override has been cleared.
	FeeTypeOverride *FeeType `json:"fee_type_override"`
}

// EventLifecycleData is the msg body for a "event_lifecycle" message.
type EventLifecycleData struct {
	// Collateral return type, MECNET or DIRECNET of the event. Empty if there is no collateral return s...
	CollateralReturnType CollateralReturnType `json:"collateral_return_type"`
	// Unique identifier for the event being created
	EventTicker string `json:"event_ticker"`
	// Series ticker for the event
	SeriesTicker string `json:"series_ticker"`
	// Optional - Unix timestamp to indicate the strike date of the event if there is one
	StrikeDate int64 `json:"strike_date,omitempty"`
	// Optional - String to indicate the strike period of the event if there is one
	StrikePeriod string `json:"strike_period,omitempty"`
	// Subtitle of event
	Subtitle string `json:"subtitle"`
	// Title of event
	Title string `json:"title"`
}

// FillData is the msg body for a "fill" message.
type FillData struct {
	// Deprecated. Use `outcome_side` (or `book_side`) instead. See [Order direction](/getting_started/o...
	// Deprecated.
	Action Action `json:"action"`
	// Same directional bit as outcome_side in book vocabulary. 'bid' is equivalent to outcome_side 'yes...
	BookSide BookSide `json:"book_side"`
	// Optional client-provided order ID
	ClientOrderID string `json:"client_order_id,omitempty"`
	// Fixed-point contracts filled (2 decimals)
	CountFP string `json:"count_fp"`
	// Exchange fee paid for this fill in fixed-point dollars
	FeeCost string `json:"fee_cost"`
	// If you were a taker on this fill
	IsTaker bool `json:"is_taker"`
	// Unique identifier for markets. This is what you use to differentiate fills for different markets
	MarketTicker string `json:"market_ticker"`
	// Unique identifier for orders. This is what you use to differentiate fills for different orders
	OrderID string `json:"order_id"`
	// The outcome side this fill positioned the user for. buy-yes and sell-no produce 'yes'; buy-no and...
	OutcomeSide Side `json:"outcome_side"`
	// Fixed-point position after the fill (2 decimals)
	PostPositionFP string `json:"post_position_fp"`
	// Deprecated. Use `outcome_side` (or `book_side`) instead. See [Order direction](/getting_started/o...
	// Deprecated.
	PurchasedSide Side `json:"purchased_side"`
	// Deprecated. Use `outcome_side` (or `book_side`) instead. See [Order direction](/getting_started/o...
	// Deprecated.
	Side Side `json:"side"`
	// Optional subaccount number for the fill
	Subaccount int `json:"subaccount,omitempty"`
	// Unique identifier for fills. This is what you use to differentiate fills
	TradeID string `json:"trade_id"`
	// Deprecated - Unix timestamp for when the update happened (in seconds). Use ts_ms instead.
	// Deprecated.
	TS int64 `json:"ts"`
	// Unix timestamp for when the update happened (in milliseconds)
	TSMs int64 `json:"ts_ms"`
	// Price for the yes side of the fill in dollars
	YesPriceDollars string `json:"yes_price_dollars"`
}

// MarketLifecycleV2Data is the msg body for a "market_lifecycle_v2" message.
type MarketLifecycleV2Data struct {
	// Optional - This key will be emitted when the market is created
	AdditionalMetadata *MarketLifecycleAdditionalMetadata `json:"additional_metadata,omitempty"`
	// Optional - This key will ONLY exist when the market is created OR when the close date is updated....
	CloseTS int64 `json:"close_ts,omitempty"`
	// Optional - This key will ONLY exist when the market is determined. Unix timestamp for when the ma...
	DeterminationTS int64 `json:"determination_ts,omitempty"`
	// Field to annotate which of the event type this event is for:
	EventType MarketLifecycleEventType `json:"event_type"`
	// Optional - This key will ONLY exist for metadata_updated events. The updated floor strike value f...
	FloorStrike float64 `json:"floor_strike,omitempty"`
	// Optional - This key will ONLY exist when the market is paused/unpaused. Boolean flag to indicate ...
	IsDeactivated *bool `json:"is_deactivated,omitempty"`
	// Unique identifier for markets. This is what you use to differentiate updates for different markets
	MarketTicker string `json:"market_ticker"`
	// Optional - This key will ONLY exist when the market is created. Unix timestamp for when the marke...
	OpenTS int64 `json:"open_ts,omitempty"`
	// Optional - This key will exist when the market is created or when the price level structure is up...
	PriceLevelStructure string `json:"price_level_structure,omitempty"`
	// Optional - This key will ONLY exist when the market is determined. Result of the market
	Result string `json:"result,omitempty"`
	// Optional - This key will ONLY exist when the market is settled. Unix timestamp for when the marke...
	SettledTS int64 `json:"settled_ts,omitempty"`
	// Optional - This key will ONLY exist when the market is determined. Settlement value of the market...
	SettlementValue string `json:"settlement_value,omitempty"`
	// Optional - This key will ONLY exist for metadata_updated events. The updated yes subtitle for the...
	YesSubTitle string `json:"yes_sub_title,omitempty"`
}

// MarketPositionData is the msg body for a "market_position" message.
type MarketPositionData struct {
	// Total fees paid as a fixed-point dollar string
	FeesPaidDollars string `json:"fees_paid_dollars"`
	// Market ticker for the position
	MarketTicker string `json:"market_ticker"`
	// Current cost basis of the position as a fixed-point dollar string
	PositionCostDollars string `json:"position_cost_dollars"`
	// Total position fee cost as a fixed-point dollar string
	PositionFeeCostDollars string `json:"position_fee_cost_dollars"`
	// Fixed-point net position (2 decimals)
	PositionFP string `json:"position_fp"`
	// Realized profit/loss as a fixed-point dollar string
	RealizedPnlDollars string `json:"realized_pnl_dollars"`
	// Optional subaccount number for the position
	Subaccount int `json:"subaccount,omitempty"`
	// User ID for the position
	UserID string `json:"user_id"`
	// Fixed-point total volume traded (2 decimals)
	VolumeFP string `json:"volume_fp"`
}

// MultivariateLookupData is the msg body for a "multivariate_lookup" message.
type MultivariateLookupData struct {
	CollectionTicker string                             `json:"collection_ticker"`
	EventTicker      string                             `json:"event_ticker"`
	MarketTicker     string                             `json:"market_ticker"`
	SelectedMarkets  []MultivariateLookupSelectedMarket `json:"selected_markets"`
}

// OrderGroupUpdateData is the msg body for a "order_group_updates" message.
type OrderGroupUpdateData struct {
	// Updated contracts limit in fixed-point (2 decimals). Present for "created" and "limit_updated" ev...
	ContractsLimitFP string `json:"contracts_limit_fp,omitempty"`
	// Order group event type
	EventType OrderGroupEventType `json:"event_type"`
	// Order group identifier
	OrderGroupID string `json:"order_group_id"`
	// Matching engine timestamp at which the event was processed, as Unix epoch milliseconds.
	TSMs int64 `json:"ts_ms"`
}

// OrderbookDeltaData is the msg body for a "orderbook_delta" message.
type OrderbookDeltaData struct {
	// Optional - Present only when you caused this orderbook change.
	ClientOrderID string `json:"client_order_id,omitempty"`
	// Fixed-point contract delta (2 decimals)
	DeltaFP      string `json:"delta_fp"`
	MarketID     string `json:"market_id"`
	MarketTicker string `json:"market_ticker"`
	// Price level in dollars
	PriceDollars string `json:"price_dollars"`
	Side         Side   `json:"side"`
	// Optional - Present only when you caused this orderbook change and are using subaccounts.
	Subaccount int `json:"subaccount,omitempty"`
	// Deprecated - Optional timestamp for when the orderbook change was recorded (RFC3339). Use ts_ms i...
	// Deprecated.
	TS string `json:"ts,omitempty"`
	// Optional - Unix timestamp for when the orderbook change was recorded (in milliseconds)
	TSMs int64 `json:"ts_ms,omitempty"`
}

// OrderbookSnapshotData is the msg body for a "orderbook_snapshot" message.
type OrderbookSnapshotData struct {
	MarketID     string `json:"market_id"`
	MarketTicker string `json:"market_ticker"`
	// Optional - Same format as "yes_dollars_fp" but for the NO side of the orderbook.
	NoDollarsFP [][]string `json:"no_dollars_fp,omitempty"`
	// Optional - This key will not exist if there are no Yes offers in the orderbook.
	YesDollarsFP [][]string `json:"yes_dollars_fp,omitempty"`
}

// QuoteAcceptedData is the msg body for a "quote_accepted" message.
type QuoteAcceptedData struct {
	// Which side was accepted (yes/no) (optional)
	AcceptedSide Side `json:"accepted_side,omitempty"`
	// Fixed-point contracts accepted (2 decimals) (optional)
	ContractsAcceptedFP string `json:"contracts_accepted_fp,omitempty"`
	// Event ticker (optional)
	EventTicker string `json:"event_ticker,omitempty"`
	// Market ticker for the quote
	MarketTicker string `json:"market_ticker"`
	// No side bid price in dollars
	NoBidDollars string `json:"no_bid_dollars"`
	// Fixed-point no contracts offered (2 decimals) (optional)
	NoContractsOfferedFP string `json:"no_contracts_offered_fp,omitempty"`
	// Public communications ID of the quote creator (anonymized)
	QuoteCreatorID string `json:"quote_creator_id"`
	// Unique identifier for the quote
	QuoteID string `json:"quote_id"`
	// Identifier of the RFQ this quote is for
	RFQID string `json:"rfq_id"`
	// Target cost from the RFQ in dollars (optional)
	RFQTargetCostDollars string `json:"rfq_target_cost_dollars,omitempty"`
	// Yes side bid price in dollars
	YesBidDollars string `json:"yes_bid_dollars"`
	// Fixed-point yes contracts offered (2 decimals) (optional)
	YesContractsOfferedFP string `json:"yes_contracts_offered_fp,omitempty"`
}

// QuoteCreatedData is the msg body for a "quote_created" message.
type QuoteCreatedData struct {
	// Timestamp when the quote was created
	CreatedTS string `json:"created_ts"`
	// Event ticker (optional)
	EventTicker string `json:"event_ticker,omitempty"`
	// Market ticker for the quote
	MarketTicker string `json:"market_ticker"`
	// No side bid price in dollars
	NoBidDollars string `json:"no_bid_dollars"`
	// Fixed-point no contracts offered (2 decimals) (optional)
	NoContractsOfferedFP string `json:"no_contracts_offered_fp,omitempty"`
	// Public communications ID of the quote creator (anonymized)
	QuoteCreatorID string `json:"quote_creator_id"`
	// Unique identifier for the quote
	QuoteID string `json:"quote_id"`
	// Identifier of the RFQ this quote is for
	RFQID string `json:"rfq_id"`
	// Target cost from the RFQ in dollars (optional)
	RFQTargetCostDollars string `json:"rfq_target_cost_dollars,omitempty"`
	// Yes side bid price in dollars
	YesBidDollars string `json:"yes_bid_dollars"`
	// Fixed-point yes contracts offered (2 decimals) (optional)
	YesContractsOfferedFP string `json:"yes_contracts_offered_fp,omitempty"`
}

// QuoteExecutedData is the msg body for a "quote_executed" message.
type QuoteExecutedData struct {
	// Your client order ID for the executed order. Use this to correlate with fill messages
	ClientOrderID string `json:"client_order_id"`
	// Timestamp when the quote was executed and orders were placed
	ExecutedTS string `json:"executed_ts"`
	// Market ticker for the executed quote
	MarketTicker string `json:"market_ticker"`
	// Your order ID resulting from the quote execution. Use this to match with fill messages
	OrderID string `json:"order_id"`
	// Anonymized identifier for the quote creator
	QuoteCreatorID string `json:"quote_creator_id"`
	// Unique identifier for the quote that was executed
	QuoteID string `json:"quote_id"`
	// Anonymized identifier for the RFQ creator
	RFQCreatorID string `json:"rfq_creator_id"`
	// Identifier of the RFQ this quote was for
	RFQID string `json:"rfq_id"`
}

// RFQCreatedData is the msg body for a "rfq_created" message.
type RFQCreatedData struct {
	// Fixed-point contracts requested (2 decimals) (optional)
	ContractsFP string `json:"contracts_fp,omitempty"`
	// Timestamp when the RFQ was created
	CreatedTS string `json:"created_ts"`
	// Public communications ID of the RFQ creator (anonymized). Currently empty for rfq_created events.
	CreatorID string `json:"creator_id"`
	// Event ticker (optional)
	EventTicker string `json:"event_ticker,omitempty"`
	// Unique identifier for the RFQ
	ID string `json:"id"`
	// Market ticker for the RFQ
	MarketTicker string `json:"market_ticker"`
	// Multivariate event collection ticker (optional)
	MVECollectionTicker string `json:"mve_collection_ticker,omitempty"`
	// Selected legs for multivariate events (optional)
	MVESelectedLegs []MveSelectedLeg `json:"mve_selected_legs,omitempty"`
	// Target cost in dollars (optional)
	TargetCostDollars string `json:"target_cost_dollars,omitempty"`
}

// RFQDeletedData is the msg body for a "rfq_deleted" message.
type RFQDeletedData struct {
	// Fixed-point contracts requested (2 decimals) (optional)
	ContractsFP string `json:"contracts_fp,omitempty"`
	// Public communications ID of the RFQ creator (anonymized)
	CreatorID string `json:"creator_id"`
	// Timestamp when the RFQ was deleted
	DeletedTS string `json:"deleted_ts"`
	// Event ticker (optional)
	EventTicker string `json:"event_ticker,omitempty"`
	// Unique identifier for the RFQ
	ID string `json:"id"`
	// Market ticker for the RFQ
	MarketTicker string `json:"market_ticker"`
	// Target cost in dollars (optional)
	TargetCostDollars string `json:"target_cost_dollars,omitempty"`
}

// TickerData is the msg body for a "ticker" message.
type TickerData struct {
	// Number of dollars positioned in the market currently
	DollarOpenInterest int `json:"dollar_open_interest"`
	// Number of dollars traded in the market so far
	DollarVolume int `json:"dollar_volume"`
	// Fixed-point contracts in last trade (2 decimals)
	LastTradeSizeFP string `json:"last_trade_size_fp"`
	MarketID        string `json:"market_id"`
	MarketTicker    string `json:"market_ticker"`
	// Fixed-point open interest (2 decimals)
	OpenInterestFP string `json:"open_interest_fp"`
	// Last traded price in dollars
	PriceDollars string `json:"price_dollars"`
	// Deprecated - Timestamp for when the update happened (RFC3339). Use ts_ms instead.
	// Deprecated.
	Time string `json:"time"`
	// Deprecated - Unix timestamp for when the update happened (in seconds). Use ts_ms instead.
	// Deprecated.
	TS int64 `json:"ts"`
	// Unix timestamp for when the update happened (in milliseconds)
	TSMs int64 `json:"ts_ms"`
	// Fixed-point total contracts traded (2 decimals)
	VolumeFP string `json:"volume_fp"`
	// Best ask price for yes side in dollars
	YesAskDollars string `json:"yes_ask_dollars"`
	// Fixed-point contracts at best ask (2 decimals)
	YesAskSizeFP string `json:"yes_ask_size_fp"`
	// Best bid price for yes side in dollars
	YesBidDollars string `json:"yes_bid_dollars"`
	// Fixed-point contracts at best bid (2 decimals)
	YesBidSizeFP string `json:"yes_bid_size_fp"`
}

// TradeData is the msg body for a "trade" message.
type TradeData struct {
	// Fixed-point contracts traded (2 decimals)
	CountFP      string `json:"count_fp"`
	MarketTicker string `json:"market_ticker"`
	// No side price in dollars
	NoPriceDollars string `json:"no_price_dollars"`
	// Same directional bit as taker_outcome_side in book vocabulary. 'bid' is equivalent to taker_outco...
	TakerBookSide BookSide `json:"taker_book_side"`
	// The outcome side the taker is positioned for. buy-yes and sell-no produce 'yes'; buy-no and sell-...
	TakerOutcomeSide Side `json:"taker_outcome_side"`
	// Deprecated. Use `taker_outcome_side` (or `taker_book_side`) instead. See [Order direction](/getti...
	// Deprecated.
	TakerSide Side `json:"taker_side"`
	// Unique identifier for the trade
	TradeID string `json:"trade_id"`
	// Deprecated - Unix timestamp in seconds. Use ts_ms instead.
	// Deprecated.
	TS int64 `json:"ts"`
	// Unix timestamp in milliseconds
	TSMs int64 `json:"ts_ms"`
	// Yes side price in dollars
	YesPriceDollars string `json:"yes_price_dollars"`
}

// UserOrderData is the msg body for a "user_order" message.
type UserOrderData struct {
	// Same directional bit as outcome_side in book vocabulary. 'bid' is equivalent to outcome_side 'yes...
	BookSide BookSide `json:"book_side"`
	// Client-provided order identifier
	ClientOrderID string `json:"client_order_id"`
	// Deprecated - Order creation time in RFC3339 format. Use created_ts_ms instead.
	// Deprecated.
	CreatedTime string `json:"created_time"`
	// Order creation time as a Unix timestamp in milliseconds
	CreatedTSMs int64 `json:"created_ts_ms"`
	// Deprecated - Order expiration time in RFC3339 format. Use expiration_ts_ms instead.
	// Deprecated.
	ExpirationTime string `json:"expiration_time,omitempty"`
	// Order expiration time as a Unix timestamp in milliseconds
	ExpirationTSMs int64 `json:"expiration_ts_ms,omitempty"`
	// Number of contracts filled in fixed-point (2 decimals)
	FillCountFP string `json:"fill_count_fp"`
	// Initial number of contracts in fixed-point (2 decimals)
	InitialCountFP string `json:"initial_count_fp"`
	// Deprecated. Use `outcome_side` (or `book_side`) instead. See [Order direction](/getting_started/o...
	// Deprecated.
	IsYes bool `json:"is_yes"`
	// Deprecated - Last update time in RFC3339 format. Use last_updated_ts_ms instead.
	// Deprecated.
	LastUpdateTime string `json:"last_update_time,omitempty"`
	// Last update time as a Unix timestamp in milliseconds
	LastUpdatedTSMs int64 `json:"last_updated_ts_ms,omitempty"`
	// Maker fees in fixed-point dollars (4 decimals).
	MakerFeesDollars string `json:"maker_fees_dollars"`
	// Maker fill cost in fixed-point dollars (4 decimals)
	MakerFillCostDollars string `json:"maker_fill_cost_dollars"`
	// Order group identifier, if applicable
	OrderGroupID string `json:"order_group_id,omitempty"`
	// Unique order identifier
	OrderID string `json:"order_id"`
	// The outcome side this order is positioned for. buy-yes and sell-no produce 'yes'; buy-no and sell...
	OutcomeSide Side `json:"outcome_side"`
	// Number of contracts remaining in fixed-point (2 decimals)
	RemainingCountFP string `json:"remaining_count_fp"`
	// Self-trade prevention type
	SelfTradePreventionType STPType `json:"self_trade_prevention_type,omitempty"`
	// Deprecated. Use `outcome_side` (or `book_side`) instead. See [Order direction](/getting_started/o...
	// Deprecated.
	Side Side `json:"side"`
	// Current order status
	Status OrderStatus `json:"status"`
	// Subaccount number (0 for primary, 1-63 for subaccounts)
	SubaccountNumber int `json:"subaccount_number,omitempty"`
	// Taker fees in fixed-point dollars (4 decimals).
	TakerFeesDollars string `json:"taker_fees_dollars"`
	// Taker fill cost in fixed-point dollars (4 decimals)
	TakerFillCostDollars string `json:"taker_fill_cost_dollars"`
	// Market ticker for the order
	Ticker string `json:"ticker"`
	// User identifier
	UserID string `json:"user_id"`
	// Yes price in fixed-point dollars (4 decimals)
	YesPriceDollars string `json:"yes_price_dollars"`
}

// MultivariateMarketLifecycleData has the same shape as MarketLifecycleV2Data.
type MultivariateMarketLifecycleData = MarketLifecycleV2Data

// ---------------------------------------------------------------------------
// Channel mapping
// ---------------------------------------------------------------------------

// MsgTypeToChannel maps incoming WS message types to the channel(s) they can arrive on.
// Also used as a set of known message types — actual routing uses SID.
var MsgTypeToChannel = map[WSMessageType][]string{
	WSMsgCfbenchmarksValue:           {"cfbenchmarks_value"},
	WSMsgCfbenchmarksValueIndexlist:  {"cfbenchmarks_value"},
	WSMsgEventFeeUpdate:              {"market_lifecycle_v2"},
	WSMsgEventLifecycle:              {"market_lifecycle_v2", "multivariate_market_lifecycle"},
	WSMsgFill:                        {"fill"},
	WSMsgMarketLifecycleV2:           {"market_lifecycle_v2"},
	WSMsgMarketPosition:              {"market_positions"},
	WSMsgMultivariateLookup:          {"multivariate"},
	WSMsgMultivariateMarketLifecycle: {"multivariate_market_lifecycle"},
	WSMsgOrderGroupUpdates:           {"order_group_updates"},
	WSMsgOrderbookDelta:              {"orderbook_delta"},
	WSMsgOrderbookSnapshot:           {"orderbook_delta"},
	WSMsgQuoteAccepted:               {"communications"},
	WSMsgQuoteCreated:                {"communications"},
	WSMsgQuoteExecuted:               {"communications"},
	WSMsgRFQCreated:                  {"communications"},
	WSMsgRFQDeleted:                  {"communications"},
	WSMsgTicker:                      {"ticker"},
	WSMsgTrade:                       {"trade"},
	WSMsgUserOrder:                   {"user_orders"},
}
